## Lectura del dataframe

In [282]:
import pandas as pd                     # Librería Pandas: Manipular de datos
from IPython.display import display     # Librería IPython: Mostrar datos en Jupyter Notebook
import datetime as dt                   # Librería datetime: Manipular fechas y horas
from fuzzywuzzy import process          # Librería fuzzywuzzy: Comparar cadenas de texto

pd.options.display.max_columns = 87     # display.max_columns sirve para mostrar la cantidad de columnas que queremos.
df_FlexDrive = pd.read_excel('../../docs/FLEX DRIVE - Permítenos Conocerte (Final - Pruebas).xlsx', sheet_name='Sheet1')
df_FlexDrive.drop(columns=['Id'], inplace=True)
df_FlexDrive.head(5)

,Hora_Inicio,Hora_Fin,P1-Autorización,P2-Edad,P3-País,P4-Ciudad,P5-Género,P6-Estrato,P7-Actividad_Actual_Multi,P8-Nivel_Educativo,P9-Frecuencia_Uso_Servicios_Públicos,P10-Servicios_Públicos_Usados_Multi,P11-Motivo_Desplazamiento_Multi,P12-Estado_Licencia_Conducción,P13-Posee_Veh_Propio,P14-Frecuencia_Uso_Veh[P13],P15-Cantidad_Veh_Propios[P13],P16-Modo_Uso_Veh[P15-U],P17-Tipo_Veh[P15-U],P18-Modo_Uso_Veh[P15-Multi],P19-Tipo_Veh[P15-Multi],P20-Conoce_P2P,P21-Beneficios_P2P,P22-Desventajas_P2P,P23-Ha_Rentado_Su_Veh,P24N-Forma_Renta[P21],P25N-Aspectos_Positivos_Exp[P21],P26N-Aspectos_Negativos_Exp2[P21],P27-Ha_Tomado_En_Renta,P28N-Lugar_donde_Rentó[P25],P29N-Entidades_Donde_Rentó[P25],P30N-Beneficios_Experiencia[P25],P31N-Desventajas_Experiencia[P25],P32-Interés_Propietario,P33-Modo_Preferido_Renta_Veh[P30],P34[A]-Prioridad:Seguro_Vehicular[P30],P34[B]-Prioridad:GPS_Vehicular[P30],P34[C]-Prioridad:Autentificar_Todos_Los_Users[P30],P34[D]-Prioridad:Seguridad_Pagos_Plataforma[P30],P34[E]-Prioridad:Comunicación_Directa_Cliente[P30],P34[F]-Prioridad:Apoyo_Precios[P30],P34[G]-Prioridad:Contratos_Automáticos[P30],P34[H]-Prioridad:Variedad_Pagos[P30],P34[I]-Prioridad:Reseñas_Clientes[P30],P34[J]-Prioridad:Contacto_FlexDrive[P30],P34[K]-Prioridad:Asistencia_Legal[P30],P34[L]-Prioridad:Apoyo_Cómo_Cobrar[P30],P35N-Otras_Prioridades[P30],P36-Modelo_Confianza_Multi[P30],P37-Precio_Horas_Propietario_Multi[P30],P38_Precio_Dia_Propietario_Multi[P30],P39_Recibir_Pagos_Propietario[P30],P40[A]-Confianza:Edad_Experiencia_Cliente[P30],P40[B]-Confianza:Antecedentes_Cliente[P30],P40[C]-Confianza:Medio_Pago_Ofertado[P30],P40[D]-Confianza:Calificación_Que_Tiene_El_Cliente[P30],P40[E]-Confianza:Motivo_Solicitud[P30],P41N-Otros_Motivos_Para_Rentar_Seguro[P30],P42-Pago_FlexDrive_Propietarios[P30],P43-Interés_Cliente,P44-Modo_Preferido_Renta_Veh[P41],P45[A]-Prioridad:Comunicación_Propietario[P41],P45[B]-Prioridad:Facilidad_Variedad_Pagos[P41],P45[C]-Prioridad:Variedad_Seguros[P41],P45[D]-Prioridad:Verificación_Usuarios[P41],P45[E]-Prioridad:Apoyo_Dudas[P42],P45[F]-Prioridad:Precios_y_Ofertas[P41],P45[G]-Prioridad:Comunicación_FlexDrive[P41],P45[H]-Prioridad:Reseñar_Propietarios[P41],P45[I]-Prioridad:Modelo_Renta_en_15MINS[P41],P45[J]-Prioridad:Modelo_Negociación[P41],P46N-Otras_Prioridades_Para_Tomar_en_Renta[41],P47-Precio_Horas_Cliente_Multi[P41],P48-Precio_Dia_Cliente_Multi[P41],P49[A]-Confianza:Negociar_con_Propietario[P41],P49[B]-Confianza:Antigüedad_Veh[P41],P49[C]-Confianza:Medio_de_Pago_Recibido[P41],P49[D]-Confianza:Reseñas_Veh[P41],P49[E]-Confianza:Reseñas_Propietario[P41],P49[F]-Confianza:Claridad_Contrato[P41],P49[G]-Confianza:Punto_Entrega_Devolución_Vehículo[P41],P49[H]-Confianza:Revisión_Tecnicomecánica_Veh[P41],P50N-Otros_Puntos_Confianza_para_Rentar[P41],P51-¿Entiende_FlexDrive?,P52-¿Usaria_FlexDrive?,P53-Preferencias_para_Comunicarse_con_FlexDrive
0,2025-05-02 16:20:11,2025-05-02 16:27:36,Acepto.,18-25,Colombia,Duitama,Femenino.,3 - (Medio),Soy estudiante en estudios superiores o univer...,Pregrado universitario (Grado o Licenciatura).,Diariamente.,Taxis;Buses intermunicipales;,Por estudio.;Por compromisos personales o fami...,Poseo licencia de conducción vigente o próxima...,No,NaN,NaN,NaN,NaN,NaN,NaN,Sí,Mayor flexibilidad en horarios.;Experiencia de...,Posibles daños o mal uso del vehículo rentado....,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,"Sí, me llama la atención en el presente o futuro.",Solo los fines de semana.;,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,NaN,Pueda configurar qué tipo de solicitudes quier...,Entre $30.000 a $50.000 la hora.;,No me encuentro interesado en rentar por días.;,"En efectivo, antes de entregar el vehículo al ...",🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,NaN,No estaría interesado en pagar comisión alguna.;,"¡Sí, me apuntaría en el presente o en el futuro!",Por días.;,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,NaN,Entre $15.000 a $30.000 la hora.;,Entre $100.000 a $150.000 el día.;,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,NaN,NaN,NaN,Clara,Probable - Me gustaría conocer más de la plata...,Por chat con asesor mediante Whatsapp.;Con un ...
1,2025-05-02 16:48:53,2025-05-02 16:54:36,Acepto.,36-45,Colombia,Duitama -Boyaca,Femenino.,2 - (Bajo - Medio),Estoy desempleado.;,Formación Técnica o Tecnológica.,Únicamente entre semana.,Taxis;Buses municipales;,Por trabajo.;,Poseo licencia de conducción vigente o próxima...,Sí,Muy rara vez.,Un único vehículo.,"Sí, es un vehículo compartido con familiares, ...","Automóvil (carros, camionetas, entre otros)",NaN,NaN,No,Mayor flexibilidad en horarios.;Posibilidad de...,Posibles daños o mal uso del vehículo rentado....,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,"No me llama la atención, gracias.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"No me llama la atención, gracias.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Clara,Neutral - Es un buen concepto que requiere más...,Por llamada telefónica.;Por chat con asesor me...
2,2025-05-02 17:13:49,2025-05-02 17:26:16,Acepto.,18-25,Colombia,"Tunja, Boyaca",Masculino.,4 - (Medio Alto),Soy freelancer / independiente.;Soy estudiante...,Pregrado universitario (Grado o Licenciatura).,Únicamente los fines de semana.,Buses intermunicipales;uber;,Por compromisos personales o familiares.;,Poseo licencia de conducción vigente o próxima...,No,NaN,NaN,NaN,NaN,NaN,NaN,No,Aprovechamiento de vehículos particulares inac...,Posibles daños o mal uso del vehículo rentado....,No,NaN,NaN,NaN,Sí,NaN,Localiza,Facilidad en el acceso al servicio.;Transparen...,Costos elevados en comparación con lo esperado.;,"Sí, me llama la atención en el presente o futuro.",Por horas.;Por días (cualquier día).;,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,NaN,Pueda configurar qué tipo de solicitudes quier...,Entre $15.000 a $30.000 la hora.;,Entre $100.000 a $150.000 el día.;,Un respaldo con un pagaré automatizado por tra...,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,NaN,No estaría interesado en pagar comisión alguna.;,"¡Sí, me apuntaría en el presente o en el futuro!",Por días.;,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🟡Prioridad Media🟡,NaN,Entre $15.000 a $30.000 la hora.;,Entre $100.000 a $150.000 el día.;,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,NaN,punto de recogida y punto de entrega del vehiculo,Clara,Muy probable - Me gustaría inscribirme en la p...,Un chat en la plataforma.;Por llamada telefóni...
3,2025-05-02 17:28:53,2025-05-02 17:33:21,Acepto.,16-17,Colombia,Tunja,Femenino.,2 - (Bajo - Medio),Soy estudiante en estudios superiores o univer...,Pregrado universitario (Grado o Licenciatura).,Únicamente los fines de semana.,Taxis;,Por estudio.;,Poseo licencia de conducción vigente o próxima...,Sí,Solo durante fines de semana.,Un único vehículo.,"No, es un vehículo completamente propio.",Moticicleta,NaN,NaN,Sí,Aprovechamiento de vehículos particulares inac...,Posibles daños o mal uso del vehículo rentado....,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,"No me llama la atención, gracias.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"No me llama la atención, gracias.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Clara,Neutral - Es un buen concepto que requiere más...,Un chat en la plataforma.;Por llamada telefóni...
4,2025-05-02 17:29:39,2025-05-02 17:33:49,Acepto.,18-25,Colombia,Tunja,Femenino.,4 - (Medio Alto),Soy estudiante en estudios superiores o univer...,Pregrado universitario (Grado o Licenciatura).,Únicamente entre semana.,Taxis;Buses municipales;,Por estudio.;,"No poseo licencia, pero estoy interesado en ob...",No,NaN,NaN,NaN,NaN,NaN,NaN,No,Posibilidad de generar ingresos como propietar...,Desconfianza frente a clientes / personas desc...,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,"No me llama la atención, gracias.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"¡Sí, me apuntaría en el presente o en el futuro!",Por horas.;,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,NaN,Entre $15.000 a $30.000 la hora.;,Entre $100.000 a $150.000 el día.;,🟡Prioridad Media🟡,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,NaN,NaN,NaN,Clara,Neutral - Es un buen concepto que requiere más...,Un chat en la plataforma.;Por correo electróni...

## Generación | Columna: Fecha de Presentación

In [283]:
# Asignando Fecha_Presentación acorde a la Hora_Inicio
df_FlexDrive['Fecha_Presentación'] = pd.to_datetime(df_FlexDrive['Hora_Inicio'].dt.date, format='%Y-%m-%d')

# Dejar duración luego de la columna 'Hora_Fin'
df_FlexDrive = df_FlexDrive[['Hora_Inicio', 'Hora_Fin', 'Fecha_Presentación'] + [col for col in df_FlexDrive.columns if col not in ['Hora_Inicio', 'Hora_Fin', 'Fecha_Presentación']]]
df_FlexDrive.head(5)

,Hora_Inicio,Hora_Fin,Fecha_Presentación,P1-Autorización,P2-Edad,P3-País,P4-Ciudad,P5-Género,P6-Estrato,P7-Actividad_Actual_Multi,P8-Nivel_Educativo,P9-Frecuencia_Uso_Servicios_Públicos,P10-Servicios_Públicos_Usados_Multi,P11-Motivo_Desplazamiento_Multi,P12-Estado_Licencia_Conducción,P13-Posee_Veh_Propio,P14-Frecuencia_Uso_Veh[P13],P15-Cantidad_Veh_Propios[P13],P16-Modo_Uso_Veh[P15-U],P17-Tipo_Veh[P15-U],P18-Modo_Uso_Veh[P15-Multi],P19-Tipo_Veh[P15-Multi],P20-Conoce_P2P,P21-Beneficios_P2P,P22-Desventajas_P2P,P23-Ha_Rentado_Su_Veh,P24N-Forma_Renta[P21],P25N-Aspectos_Positivos_Exp[P21],P26N-Aspectos_Negativos_Exp2[P21],P27-Ha_Tomado_En_Renta,P28N-Lugar_donde_Rentó[P25],P29N-Entidades_Donde_Rentó[P25],P30N-Beneficios_Experiencia[P25],P31N-Desventajas_Experiencia[P25],P32-Interés_Propietario,P33-Modo_Preferido_Renta_Veh[P30],P34[A]-Prioridad:Seguro_Vehicular[P30],P34[B]-Prioridad:GPS_Vehicular[P30],P34[C]-Prioridad:Autentificar_Todos_Los_Users[P30],P34[D]-Prioridad:Seguridad_Pagos_Plataforma[P30],P34[E]-Prioridad:Comunicación_Directa_Cliente[P30],P34[F]-Prioridad:Apoyo_Precios[P30],P34[G]-Prioridad:Contratos_Automáticos[P30],P34[H]-Prioridad:Variedad_Pagos[P30],P34[I]-Prioridad:Reseñas_Clientes[P30],P34[J]-Prioridad:Contacto_FlexDrive[P30],P34[K]-Prioridad:Asistencia_Legal[P30],P34[L]-Prioridad:Apoyo_Cómo_Cobrar[P30],P35N-Otras_Prioridades[P30],P36-Modelo_Confianza_Multi[P30],P37-Precio_Horas_Propietario_Multi[P30],P38_Precio_Dia_Propietario_Multi[P30],P39_Recibir_Pagos_Propietario[P30],P40[A]-Confianza:Edad_Experiencia_Cliente[P30],P40[B]-Confianza:Antecedentes_Cliente[P30],P40[C]-Confianza:Medio_Pago_Ofertado[P30],P40[D]-Confianza:Calificación_Que_Tiene_El_Cliente[P30],P40[E]-Confianza:Motivo_Solicitud[P30],P41N-Otros_Motivos_Para_Rentar_Seguro[P30],P42-Pago_FlexDrive_Propietarios[P30],P43-Interés_Cliente,P44-Modo_Preferido_Renta_Veh[P41],P45[A]-Prioridad:Comunicación_Propietario[P41],P45[B]-Prioridad:Facilidad_Variedad_Pagos[P41],P45[C]-Prioridad:Variedad_Seguros[P41],P45[D]-Prioridad:Verificación_Usuarios[P41],P45[E]-Prioridad:Apoyo_Dudas[P42],P45[F]-Prioridad:Precios_y_Ofertas[P41],P45[G]-Prioridad:Comunicación_FlexDrive[P41],P45[H]-Prioridad:Reseñar_Propietarios[P41],P45[I]-Prioridad:Modelo_Renta_en_15MINS[P41],P45[J]-Prioridad:Modelo_Negociación[P41],P46N-Otras_Prioridades_Para_Tomar_en_Renta[41],P47-Precio_Horas_Cliente_Multi[P41],P48-Precio_Dia_Cliente_Multi[P41],P49[A]-Confianza:Negociar_con_Propietario[P41],P49[B]-Confianza:Antigüedad_Veh[P41],P49[C]-Confianza:Medio_de_Pago_Recibido[P41],P49[D]-Confianza:Reseñas_Veh[P41],P49[E]-Confianza:Reseñas_Propietario[P41],P49[F]-Confianza:Claridad_Contrato[P41],P49[G]-Confianza:Punto_Entrega_Devolución_Vehículo[P41],P49[H]-Confianza:Revisión_Tecnicomecánica_Veh[P41],P50N-Otros_Puntos_Confianza_para_Rentar[P41],P51-¿Entiende_FlexDrive?,P52-¿Usaria_FlexDrive?,P53-Preferencias_para_Comunicarse_con_FlexDrive
0,2025-05-02 16:20:11,2025-05-02 16:27:36,2025-05-02,Acepto.,18-25,Colombia,Duitama,Femenino.,3 - (Medio),Soy estudiante en estudios superiores o univer...,Pregrado universitario (Grado o Licenciatura).,Diariamente.,Taxis;Buses intermunicipales;,Por estudio.;Por compromisos personales o fami...,Poseo licencia de conducción vigente o próxima...,No,NaN,NaN,NaN,NaN,NaN,NaN,Sí,Mayor flexibilidad en horarios.;Experiencia de...,Posibles daños o mal uso del vehículo rentado....,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,"Sí, me llama la atención en el presente o futuro.",Solo los fines de semana.;,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,NaN,Pueda configurar qué tipo de solicitudes quier...,Entre $30.000 a $50.000 la hora.;,No me encuentro interesado en rentar por días.;,"En efectivo, antes de entregar el vehículo al ...",🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,NaN,No estaría interesado en pagar comisión alguna.;,"¡Sí, me apuntaría en el presente o en el futuro!",Por días.;,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,NaN,Entre $15.000 a $30.000 la hora.;,Entre $100.000 a $150.000 el día.;,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,NaN,NaN,NaN,Clara,Probable - Me gustaría conocer más de la plata...,Por chat con asesor mediante Whatsapp.;Con un ...
1,2025-05-02 16:48:53,2025-05-02 16:54:36,2025-05-02,Acepto.,36-45,Colombia,Duitama -Boyaca,Femenino.,2 - (Bajo - Medio),Estoy desempleado.;,Formación Técnica o Tecnológica.,Únicamente entre semana.,Taxis;Buses municipales;,Por trabajo.;,Poseo licencia de conducción vigente o próxima...,Sí,Muy rara vez.,Un único vehículo.,"Sí, es un vehículo compartido con familiares, ...","Automóvil (carros, camionetas, entre otros)",NaN,NaN,No,Mayor flexibilidad en horarios.;Posibilidad de...,Posibles daños o mal uso del vehículo rentado....,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,"No me llama la atención, gracias.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"No me llama la atención, gracias.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Clara,Neutral - Es un buen concepto que requiere más...,Por llamada telefónica.;Por chat con asesor me...
2,2025-05-02 17:13:49,2025-05-02 17:26:16,2025-05-02,Acepto.,18-25,Colombia,"Tunja, Boyaca",Masculino.,4 - (Medio Alto),Soy freelancer / independiente.;Soy estudiante...,Pregrado universitario (Grado o Licenciatura).,Únicamente los fines de semana.,Buses intermunicipales;uber;,Por compromisos personales o familiares.;,Poseo licencia de conducción vigente o próxima...,No,NaN,NaN,NaN,NaN,NaN,NaN,No,Aprovechamiento de vehículos particulares inac...,Posibles daños o mal uso del vehículo rentado....,No,NaN,NaN,NaN,Sí,NaN,Localiza,Facilidad en el acceso al servicio.;Transparen...,Costos elevados en comparación con lo esperado.;,"Sí, me llama la atención en el presente o futuro.",Por horas.;Por días (cualquier día).;,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,NaN,Pueda configurar qué tipo de solicitudes quier...,Entre $15.000 a $30.000 la hora.;,Entre $100.000 a $150.000 el día.;,Un respaldo con un pagaré automatizado por tra...,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,NaN,No estaría interesado en pagar comisión alguna.;,"¡Sí, me apuntaría en el presente o en el futuro!",Por días.;,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🟡Prioridad Media🟡,NaN,Entre $15.000 a $30.000 la hora.;,Entre $100.000 a $150.000 el día.;,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,NaN,punto de recogida y punto de entrega del vehiculo,Clara,Muy probable - Me gustaría inscribirme en la p...,Un chat en la plataforma.;Por llamada telefóni...
3,2025-05-02 17:28:53,2025-05-02 17:33:21,2025-05-02,Acepto.,16-17,Colombia,Tunja,Femenino.,2 - (Bajo - Medio),Soy estudiante en estudios superiores o univer...,Pregrado universitario (Grado o Licenciatura).,Únicamente los fines de semana.,Taxis;,Por estudio.;,Poseo licencia de conducción vigente o próxima...,Sí,Solo durante fines de semana.,Un único vehículo.,"No, es un vehículo completamente propio.",Moticicleta,NaN,NaN,Sí,Aprovechamiento de vehículos particulares inac...,Posibles daños o mal uso del vehículo rentado....,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,"No me llama la atención, gracias.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"No me llama la atención, gracias.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Clara,Neutral - Es un buen concepto que requiere más...,Un chat en la plataforma.;Por llamada telefóni...
4,2025-05-02 17:29:39,2025-05-02 17:33:49,2025-05-02,Acepto.,18-25,Colombia,Tunja,Femenino.,4 - (Medio Alto),Soy estudiante en estudios superiores o univer...,Pregrado universitario (Grado o Licenciatura).,Únicamente entre semana.,Taxis;Buses municipales;,Por estudio.;,"No poseo licencia, pero estoy interesado en ob...",No,NaN,NaN,NaN,NaN,NaN,NaN,No,Posibilidad de generar ingresos como propietar...,Desconfianza frente a clientes / personas desc...,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,"No me llama la atención, gracias.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"¡Sí, me apuntaría en el presente o en el futuro!",Por horas.;,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,NaN,Entre $15.000 a $30.000 la hora.;,Entre $100.000 a $150.000 el día.;,🟡Prioridad Media🟡,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,NaN,NaN,NaN,Clara,Neutral - Es un buen concepto que requiere más...,Un chat en la plataforma.;Por correo electróni...

## Generación | Columna: Duracción_mmss
Se usa la librería datetime. Se dispone luego de la duración. El siguiente segmento de código elimina HORA_INICIO y HORA_FIN, para dejar únicamente la fecha en que lo presentó.

In [284]:
# Convertir la columna 'Hora_Inicio' a tipo datetime
df_FlexDrive['Hora_Inicio'] = pd.to_datetime(df_FlexDrive['Hora_Inicio'], format='%H:%M:%S', errors='coerce')
df_FlexDrive['Hora_Fin'] = pd.to_datetime(df_FlexDrive['Hora_Fin'], format='%H:%M:%S', errors='coerce')

# Asignar duración en minutos y segundos a todo el dataframe
duracion = df_FlexDrive['Hora_Fin'] - df_FlexDrive['Hora_Inicio']

# Presentando duración en formato mm:ss
df_FlexDrive['Duración_mmss'] = duracion.apply(
	lambda x: f"{int(x.total_seconds() // 60):02d}:{int(x.total_seconds() % 60):02d}" if pd.notnull(x) else None
)

# Dejar duración luego de la columna 'Hora_Fin'
df_FlexDrive.drop(columns=['Hora_Inicio', 'Hora_Fin'], inplace=True)
df_FlexDrive = df_FlexDrive[['Fecha_Presentación', 'Duración_mmss'] + [col for col in df_FlexDrive.columns if col not in ['Fecha_Presentación', 'Duración_mmss']]]
df_FlexDrive.head(5)

,Fecha_Presentación,Duración_mmss,P1-Autorización,P2-Edad,P3-País,P4-Ciudad,P5-Género,P6-Estrato,P7-Actividad_Actual_Multi,P8-Nivel_Educativo,P9-Frecuencia_Uso_Servicios_Públicos,P10-Servicios_Públicos_Usados_Multi,P11-Motivo_Desplazamiento_Multi,P12-Estado_Licencia_Conducción,P13-Posee_Veh_Propio,P14-Frecuencia_Uso_Veh[P13],P15-Cantidad_Veh_Propios[P13],P16-Modo_Uso_Veh[P15-U],P17-Tipo_Veh[P15-U],P18-Modo_Uso_Veh[P15-Multi],P19-Tipo_Veh[P15-Multi],P20-Conoce_P2P,P21-Beneficios_P2P,P22-Desventajas_P2P,P23-Ha_Rentado_Su_Veh,P24N-Forma_Renta[P21],P25N-Aspectos_Positivos_Exp[P21],P26N-Aspectos_Negativos_Exp2[P21],P27-Ha_Tomado_En_Renta,P28N-Lugar_donde_Rentó[P25],P29N-Entidades_Donde_Rentó[P25],P30N-Beneficios_Experiencia[P25],P31N-Desventajas_Experiencia[P25],P32-Interés_Propietario,P33-Modo_Preferido_Renta_Veh[P30],P34[A]-Prioridad:Seguro_Vehicular[P30],P34[B]-Prioridad:GPS_Vehicular[P30],P34[C]-Prioridad:Autentificar_Todos_Los_Users[P30],P34[D]-Prioridad:Seguridad_Pagos_Plataforma[P30],P34[E]-Prioridad:Comunicación_Directa_Cliente[P30],P34[F]-Prioridad:Apoyo_Precios[P30],P34[G]-Prioridad:Contratos_Automáticos[P30],P34[H]-Prioridad:Variedad_Pagos[P30],P34[I]-Prioridad:Reseñas_Clientes[P30],P34[J]-Prioridad:Contacto_FlexDrive[P30],P34[K]-Prioridad:Asistencia_Legal[P30],P34[L]-Prioridad:Apoyo_Cómo_Cobrar[P30],P35N-Otras_Prioridades[P30],P36-Modelo_Confianza_Multi[P30],P37-Precio_Horas_Propietario_Multi[P30],P38_Precio_Dia_Propietario_Multi[P30],P39_Recibir_Pagos_Propietario[P30],P40[A]-Confianza:Edad_Experiencia_Cliente[P30],P40[B]-Confianza:Antecedentes_Cliente[P30],P40[C]-Confianza:Medio_Pago_Ofertado[P30],P40[D]-Confianza:Calificación_Que_Tiene_El_Cliente[P30],P40[E]-Confianza:Motivo_Solicitud[P30],P41N-Otros_Motivos_Para_Rentar_Seguro[P30],P42-Pago_FlexDrive_Propietarios[P30],P43-Interés_Cliente,P44-Modo_Preferido_Renta_Veh[P41],P45[A]-Prioridad:Comunicación_Propietario[P41],P45[B]-Prioridad:Facilidad_Variedad_Pagos[P41],P45[C]-Prioridad:Variedad_Seguros[P41],P45[D]-Prioridad:Verificación_Usuarios[P41],P45[E]-Prioridad:Apoyo_Dudas[P42],P45[F]-Prioridad:Precios_y_Ofertas[P41],P45[G]-Prioridad:Comunicación_FlexDrive[P41],P45[H]-Prioridad:Reseñar_Propietarios[P41],P45[I]-Prioridad:Modelo_Renta_en_15MINS[P41],P45[J]-Prioridad:Modelo_Negociación[P41],P46N-Otras_Prioridades_Para_Tomar_en_Renta[41],P47-Precio_Horas_Cliente_Multi[P41],P48-Precio_Dia_Cliente_Multi[P41],P49[A]-Confianza:Negociar_con_Propietario[P41],P49[B]-Confianza:Antigüedad_Veh[P41],P49[C]-Confianza:Medio_de_Pago_Recibido[P41],P49[D]-Confianza:Reseñas_Veh[P41],P49[E]-Confianza:Reseñas_Propietario[P41],P49[F]-Confianza:Claridad_Contrato[P41],P49[G]-Confianza:Punto_Entrega_Devolución_Vehículo[P41],P49[H]-Confianza:Revisión_Tecnicomecánica_Veh[P41],P50N-Otros_Puntos_Confianza_para_Rentar[P41],P51-¿Entiende_FlexDrive?,P52-¿Usaria_FlexDrive?,P53-Preferencias_para_Comunicarse_con_FlexDrive
0,2025-05-02,07:25,Acepto.,18-25,Colombia,Duitama,Femenino.,3 - (Medio),Soy estudiante en estudios superiores o univer...,Pregrado universitario (Grado o Licenciatura).,Diariamente.,Taxis;Buses intermunicipales;,Por estudio.;Por compromisos personales o fami...,Poseo licencia de conducción vigente o próxima...,No,NaN,NaN,NaN,NaN,NaN,NaN,Sí,Mayor flexibilidad en horarios.;Experiencia de...,Posibles daños o mal uso del vehículo rentado....,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,"Sí, me llama la atención en el presente o futuro.",Solo los fines de semana.;,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,NaN,Pueda configurar qué tipo de solicitudes quier...,Entre $30.000 a $50.000 la hora.;,No me encuentro interesado en rentar por días.;,"En efectivo, antes de entregar el vehículo al ...",🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,NaN,No estaría interesado en pagar comisión alguna.;,"¡Sí, me apuntaría en el presente o en el futuro!",Por días.;,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,NaN,Entre $15.000 a $30.000 la hora.;,Entre $100.000 a $150.000 el día.;,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,NaN,NaN,NaN,Clara,Probable - Me gustaría conocer más de la plata...,Por chat con asesor mediante Whatsapp.;Con un ...
1,2025-05-02,05:43,Acepto.,36-45,Colombia,Duitama -Boyaca,Femenino.,2 - (Bajo - Medio),Estoy desempleado.;,Formación Técnica o Tecnológica.,Únicamente entre semana.,Taxis;Buses municipales;,Por trabajo.;,Poseo licencia de conducción vigente o próxima...,Sí,Muy rara vez.,Un único vehículo.,"Sí, es un vehículo compartido con familiares, ...","Automóvil (carros, camionetas, entre otros)",NaN,NaN,No,Mayor flexibilidad en horarios.;Posibilidad de...,Posibles daños o mal uso del vehículo rentado....,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,"No me llama la atención, gracias.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"No me llama la atención, gracias.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Clara,Neutral - Es un buen concepto que requiere más...,Por llamada telefónica.;Por chat con asesor me...
2,2025-05-02,12:27,Acepto.,18-25,Colombia,"Tunja, Boyaca",Masculino.,4 - (Medio Alto),Soy freelancer / independiente.;Soy estudiante...,Pregrado universitario (Grado o Licenciatura).,Únicamente los fines de semana.,Buses intermunicipales;uber;,Por compromisos personales o familiares.;,Poseo licencia de conducción vigente o próxima...,No,NaN,NaN,NaN,NaN,NaN,NaN,No,Aprovechamiento de vehículos particulares inac...,Posibles daños o mal uso del vehículo rentado....,No,NaN,NaN,NaN,Sí,NaN,Localiza,Facilidad en el acceso al servicio.;Transparen...,Costos elevados en comparación con lo esperado.;,"Sí, me llama la atención en el presente o futuro.",Por horas.;Por días (cualquier día).;,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,NaN,Pueda configurar qué tipo de solicitudes quier...,Entre $15.000 a $30.000 la hora.;,Entre $100.000 a $150.000 el día.;,Un respaldo con un pagaré automatizado por tra...,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,NaN,No estaría interesado en pagar comisión alguna.;,"¡Sí, me apuntaría en el presente o en el futuro!",Por días.;,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🟡Prioridad Media🟡,NaN,Entre $15.000 a $30.000 la hora.;,Entre $100.000 a $150.000 el día.;,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,NaN,punto de recogida y punto de entrega del vehiculo,Clara,Muy probable - Me gustaría inscribirme en la p...,Un chat en la plataforma.;Por llamada telefóni...
3,2025-05-02,04:28,Acepto.,16-17,Colombia,Tunja,Femenino.,2 - (Bajo - Medio),Soy estudiante en estudios superiores o univer...,Pregrado universitario (Grado o Licenciatura).,Únicamente los fines de semana.,Taxis;,Por estudio.;,Poseo licencia de conducción vigente o próxima...,Sí,Solo durante fines de semana.,Un único vehículo.,"No, es un vehículo completamente propio.",Moticicleta,NaN,NaN,Sí,Aprovechamiento de vehículos particulares inac...,Posibles daños o mal uso del vehículo rentado....,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,"No me llama la atención, gracias.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"No me llama la atención, gracias.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Clara,Neutral - Es un buen concepto que requiere más...,Un chat en la plataforma.;Por llamada telefóni...
4,2025-05-02,04:10,Acepto.,18-25,Colombia,Tunja,Femenino.,4 - (Medio Alto),Soy estudiante en estudios superiores o univer...,Pregrado universitario (Grado o Licenciatura).,Únicamente entre semana.,Taxis;Buses municipales;,Por estudio.;,"No poseo licencia, pero estoy interesado en ob...",No,NaN,NaN,NaN,NaN,NaN,NaN,No,Posibilidad de generar ingresos como propietar...,Desconfianza frente a clientes / personas desc...,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,"No me llama la atención, gracias.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"¡Sí, me apuntaría en el presente o en el futuro!",Por horas.;,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,NaN,Entre $15.000 a $30.000 la hora.;,Entre $100.000 a $150.000 el día.;,🟡Prioridad Media🟡,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,NaN,NaN,NaN,Clara,Neutral - Es un buen concepto que requiere más...,Un chat en la plataforma.;Por correo electróni...

## Conteo | Fecha de Presentación

In [285]:
# Conteo de respuestas (por agrupación) en la columna 'Fecha_Presentación'
display(df_FlexDrive["Fecha_Presentación"].value_counts())

Fecha_Presentación
2025-05-22    64
2025-05-20    50
2025-05-24    44
2025-05-02    26
2025-05-16    24
2025-05-23    23
2025-05-19    22
2025-05-03    22
2025-05-18    20
2025-05-05    20
2025-05-12    18
2025-05-17    15
2025-05-21    12
2025-05-08     7
2025-05-04     7
2025-05-26     6
2025-05-06     4
2025-05-25     4
2025-05-09     3
2025-05-07     2
2025-05-27     2
Name: count, dtype: int64

## Conteo | Duración contestando el Formulario

In [286]:
# Conteo de duración en minutos, agrupados en rangos de 2 minutos
df_FlexDrive['Duración_Minutos'] = df_FlexDrive['Duración_mmss'].apply(lambda x: int(x.split(':')[0]) if pd.notnull(x) else 0)
df_FlexDrive['Duración_Rango'] = pd.cut(df_FlexDrive['Duración_Minutos'], bins=range(0, 61, 2), right=False, include_lowest=True)

# Conteo de duración en minutos agrupados en rangos de 2 minutos
display(df_FlexDrive['Duración_Rango'].value_counts().sort_index())

Duración_Rango
[0, 2)      13
[2, 4)      57
[4, 6)      67
[6, 8)      76
[8, 10)     39
[10, 12)    37
[12, 14)    29
[14, 16)    16
[16, 18)    13
[18, 20)    11
[20, 22)     5
[22, 24)     8
[24, 26)     1
[26, 28)     0
[28, 30)     2
[30, 32)     0
[32, 34)     4
[34, 36)     1
[36, 38)     1
[38, 40)     1
[40, 42)     2
[42, 44)     2
[44, 46)     2
[46, 48)     0
[48, 50)     0
[50, 52)     1
[52, 54)     0
[54, 56)     0
[56, 58)     0
[58, 60)     0
Name: count, dtype: int64

# Conteo | P1- Autorización para el Tratamiento de Datos

In [287]:
# Conteo de respuestas en la columna 'P1-Autorización'
display(df_FlexDrive["P1-Autorización"].value_counts())

P1-Autorización
Acepto.       390
No acepto.      5
Name: count, dtype: int64

## Conteo 2 | P2- Edad del encuestado

In [288]:
# Conteo de respuestas en la columna 'P2-Edad'
display(df_FlexDrive["P2-Edad"].value_counts())

P2-Edad
18-25              213
26-35               47
46-55               44
36-45               37
16-17               24
56-65               21
76 en adelante.      2
66-75                2
Name: count, dtype: int64

## Funcionalidad para Limpieza de Datos Múltiples

In [289]:
def limpieza_respuestas_multi(serie):
    return (
        serie
        .fillna('')  # reemplazar NaN
        .astype(str)
        .str.replace(r'\s*;\s*', ';', regex=True)  # Quitar espacios alrededor de ;
        .str.replace(r'\.;', ';', regex=True)      # Quitar punto antes del ;
        .str.replace(r';$', '', regex=True)        # Quitar ; final
        .str.replace(r'\.$', '', regex=True)       # Quitar punto final
        .str.strip()
        .str.split(';')                            # Separar por ;
    )


def limpieza_preguntas_multi(df, columna):
    serie_limpia = limpieza_respuestas_multi(df[columna])
    
    ocupaciones_exploded = serie_limpia.explode().str.strip()
    conteo_ocupaciones = ocupaciones_exploded.value_counts()
    
    print(f"{conteo_ocupaciones}\n\nTotal de respuestas únicas: {len(conteo_ocupaciones)}")
    return serie_limpia


def mapeo_respuestas(df, columna, mapeo):
    
    def reemplazar_respuestas(lista_original):
        resultado = []
        for item in lista_original:
            item = item.strip()
            if item in mapeo:
                resultado.extend(mapeo[item])
            else:
                resultado.append(item)
        return list(dict.fromkeys([i.strip() for i in resultado if i]))

    # Limpiar y dividir
    serie_limpia = limpieza_respuestas_multi(df[columna])
    
    # Mapear
    serie_mapeada = serie_limpia.apply(reemplazar_respuestas)
    
    # Unir de nuevo como string separado por ";"
    df[columna] = serie_mapeada.apply(lambda x: ';'.join(x))

    return df

## Limpieza y Conteo | P3- Nacionalidad

In [290]:
mapeo_nacionalidades = {
    "Angola": [""],
    "India": [""],
    "Afganistán": [""],
    
    "Comoras": ["Colombia"],
}


# Aplicar el mapeo a la columna 'P7-Actividad_Actual_Multi'
df_FlexDrive = mapeo_respuestas(df_FlexDrive, "P3-País", mapeo_nacionalidades)

# Eliminar filas donde 'P3-País' está vacío (cadena vacía o NaN)
df_FlexDrive = df_FlexDrive[df_FlexDrive["P3-País"].notna() & (df_FlexDrive["P3-País"] != "")].copy()


# Conteo de respuestas en la columna 'P3-País'
display(df_FlexDrive["P3-País"].value_counts())

P3-País
Colombia     381
México         2
Ecuador        2
Guatemala      1
Honduras       1
Name: count, dtype: int64

In [291]:
df_FlexDrive["P4-Ciudad"].unique()

array(['Duitama ', 'Duitama -Boyaca ', 'Tunja, Boyaca', 'Tunja', 'Tunja ',
       'Yopal', 'Yopal ', 'Villavicencio ', 'Bogotá ', 'Fusagasuga',
       'Sogamoso', 'Sogamoso ', 'Duitama -Boyaca', 'Cucuta ',
       'Bogotá DC ', 'Duitama', 'Colombia ', 'Duitama (Boyacá)', 'YOPAL',
       'Bucaramanga ', 'Bogotá', 'Bogota ', 'Yopal Casanare', 'Bogota',
       'Medellín ', 'Paipa Boyaca', 'Tu jefe ', 'Combita ', 'TUNJA',
       'Barrancabermeja', 'Barrancabermeja ', 'Boyaca', 'Ventaqueda ',
       'Ventaquemada ', 'Riobamba ', 'El Carmen', 'Guatemala ',
       'Catacamas', 'Barbosa ', 'Tenjo Cundinamarca ', 'Tu ja', 'Túnja',
       'Cómbita', 'Tunja Boyaca', 'Guanajuato', 'Sogamoso, Boyacá ',
       'Paipa', 'tunja', 'Barbosa', 'Chia', 'Rusia', 'Kazan ',
       'Australia ', 'Gold Coast, australia', 'Villanueva casanare ',
       'Facatativá ', 'Tibasosa ', 'Cajicá', 'Rusia ', 'Russia', 'Funza',
       'Paz de rio ', 'Pazderio ', 'Nobsa ', 'Tasco', 'Guateque',
       'La capilla boyaca ', 'Paz de rio Boyacá ',
       'Cucuta norte de Santander ', 'Paz de rio boyacá',
       'Puerto Boyacá ', 'Boyacá ', 'Socha', 'Samacá ', 'Samaca ',
       'Paz de río ', 'Santa Rosa de Viterbo ', 'Armenia ', 'DUITAMA ',
       'Santa Rosa de Viterbo', 'San juan bosco ', 'Duitama Boyaca',
       'Duitama boyaca ', 'Santa Rosa de viterbo ', 'Barranquilla ',
       'duitama ', 'Floridablanca ', 'Medellín',
       'El Tarra, Norte de Santander', 'Bogotà ', 'Diutama', 'DUITAMA',
       'Colombia', 'Tame'], dtype=object)

## Limpieza de P4 - Ciudad de Origen

In [292]:
# Mostrando las ciudades únicas en la columna 'P4-Ciudad' en orden alfabético 
df_FlexDrive['P4-Ciudad'] = df_FlexDrive['P4-Ciudad'].str.strip()  # Eliminar espacios en blanco al inicio y al final
df_FlexDrive['P4-Ciudad'] = df_FlexDrive['P4-Ciudad'].str.title()  # Capitalizar la primera letra de cada palabra

In [293]:
# Lista de ciudades válidas, puedes comenzar con las más comunes en tu región
ciudades_validas = ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Bucaramanga', 'Manizales', 'Tunja', 'Villavicencio']

# Crear diccionario de corrección automática
diccionario_ciudades = {}
for ciudad in df_FlexDrive['P4-Ciudad'].unique():
    if pd.isnull(ciudad):
        diccionario_ciudades[ciudad] = ciudad  # Mantener NaN
        continue
    mejor_match, score = process.extractOne(ciudad, ciudades_validas)
    if score > 85:  # puedes ajustar el umbral según tu confianza
        diccionario_ciudades[ciudad] = mejor_match
    else:
        diccionario_ciudades[ciudad] = ciudad  # queda igual si no hay buen match

# Aplicar correcciones
pd.Series(diccionario_ciudades).to_csv("diccionario_ciudades.csv")

In [294]:
# Cargar el diccionario de ciudades desde el CSV
diccionario_ciudades = pd.read_csv('diccionario_oficial_ciudades.csv', index_col=0).squeeze().to_dict()

#Mostrar el diccionario de ciudades
print(diccionario_ciudades)

# Aplicar el diccionario de corrección a la columna 'P4-Ciudad'
df_FlexDrive['P4-Ciudad'] = df_FlexDrive['P4-Ciudad'].map(diccionario_ciudades)
# Mostrar las primeras filas del DataFrame con la columna 'P4-Ciudad' corregida
df_FlexDrive["P4-Ciudad"].value_counts().sort_index(ascending=True)

{'Armenia': 'Armenia (Quindío)', 'Australia': nan, 'Barbosa': 'Barbosa (Santander)', 'Barrancabermeja': 'Barrancabermeja (Santander)', 'Barranquilla': 'Barranquilla (Atlántico)', 'Bie': nan, 'Bogota': 'Bogotá D.C.', 'Bogotà': 'Bogotá D.C.', 'Bogotá': 'Bogotá D.C.', 'Bogotá Dc': 'Bogotá D.C.', 'Boyaca': 'Boyacá (Boyacá)', 'Boyacá': 'Boyacá (Boyacá)', 'Bucaramanga': 'Bucaramanga (Santander)', 'Cajicá': 'Cajicá (Cundinamarca)', 'Catacamas': 'Catacamas (Honduras)', 'Chia': 'Chía (Cundinamarca)', 'Colombia': nan, 'Cucuta': 'Cúcuta (Norte De Santander)', 'Cucuta Norte De Santander': 'Cúcuta (Norte De Santander)', 'Combita': 'Cómbita (Boyacá)', 'Cómbita': 'Cómbita (Boyacá)', 'Diutama': 'Duitama (Boyacá)', 'Duitama': 'Duitama (Boyacá)', 'Duitama (Boyacá)': 'Duitama (Boyacá)', 'Duitama -Boyaca': 'Duitama (Boyacá)', 'Duitama Boyaca': 'Duitama (Boyacá)', 'El Carmen': 'El Carmen (Norte De Santander)', 'El Tarra, Norte De Santander': 'El Tarra (Norte De Santander)', 'Facatativá': 'Facatativá (Cundinamarca)', 'Floridablanca': 'Floridablanca (Santander)', 'Funza': 'Funza (Cundinamarca)', 'Fusagasuga': 'Fusagasuga (Cundinamarca)', 'Gold Coast, Australia': 'Gold Coast (Australia)', 'Guanajuato': 'Guanajuato (México)', 'Guatemala': 'Ciudad de Guatemala (Guatemala)', 'Guateque': 'Guateque (Boyacá)', 'Kazan': 'Kazan (Rusia)', 'La Capilla Boyaca': 'La Capilla (Boyacá)', 'Medellín': 'Medellín (Antioquia)', 'Nobsa': 'Nobsa (Boyacá)', 'Paipa': 'Paipa (Boyacá)', 'Paipa Boyaca': 'Paipa (Boyacá)', 'Paz De Rio': 'Paz De Río (Boyacá)', 'Paz De Rio Boyacá': 'Paz De Río (Boyacá)', 'Paz De Río': 'Paz De Río (Boyacá)', 'Pazderio': 'Paz De Río (Boyacá)', 'Puerto Boyacá': 'Puerto Boyacá (Boyacá)', 'Riobamba': 'Riobamba (Ecuador)', 'Rusia': 'Rusia', 'Russia': 'Rusia', 'Samaca': 'Samacá (Boyacá)', 'Samacá': 'Samacá (Boyacá)', 'San Juan Bosco': 'San Juan Bosco (Boyacá)', 'Santa Rosa De Viterbo': 'Santa Rosa De Viterbo (Boyacá)', 'Socha': 'Socha (Boyacá)', 'Sogamoso': 'Sogamoso (Boyacá)', 'Sogamoso, Boyacá': 'Sogamoso (Boyacá)', 'Tasco': 'Tasco (Boyacá)', 'Tenjo Cundinamarca': 'Tenjo (Cundinamarca)', 'Tibasosa': 'Tibasosa (Boyacá)', 'Tu Jefe': nan, 'Tu Ja': 'Tunja (Boyacá)', 'Tunja': 'Tunja (Boyacá)', 'Tunja Boyaca': 'Tunja (Boyacá)', 'Tunja, Boyaca': 'Tunja (Boyacá)', 'Túnja': 'Tunja (Boyacá)', 'Ventaqueda': 'Ventaquemada (Boyacá)', 'Ventaquemada': 'Ventaquemada (Boyacá)', 'Villanueva Casanare': 'Villanueva (Casanare)', 'Villavicencio': 'Villavicencio (Meta)', 'Yopal': 'Yopal (Casanare)', 'Yopal Casanare': 'Yopal (Casanare)', nan: nan}

P4-Ciudad
Armenia (Quindío)                    1
Barbosa (Santander)                  3
Barrancabermeja (Santander)          2
Barranquilla (Atlántico)             2
Bogotá D.C.                         46
Boyacá (Boyacá)                      2
Bucaramanga (Santander)              3
Cajicá (Cundinamarca)                1
Catacamas (Honduras)                 1
Chía (Cundinamarca)                  1
Ciudad de Guatemala (Guatemala)      1
Cómbita (Boyacá)                     3
Cúcuta (Norte De Santander)          2
Duitama (Boyacá)                    50
El Carmen (Norte De Santander)       1
El Tarra (Norte De Santander)        1
Facatativá (Cundinamarca)            1
Floridablanca (Santander)            2
Funza (Cundinamarca)                 1
Fusagasuga (Cundinamarca)            1
Gold Coast (Australia)               1
Guanajuato (México)                  1
Guateque (Boyacá)                    1
Kazan (Rusia)                        1
La Capilla (Boyacá)                  1
Medellín (Antioquia)                 3
Nobsa (Boyacá)                       1
Paipa (Boyacá)                       2
Paz De Río (Boyacá)                  5
Puerto Boyacá (Boyacá)               1
Riobamba (Ecuador)                   1
Rusia                                3
Samacá (Boyacá)                      2
San Juan Bosco (Boyacá)              1
Santa Rosa De Viterbo (Boyacá)       3
Socha (Boyacá)                       2
Sogamoso (Boyacá)                   24
Tasco (Boyacá)                       2
Tenjo (Cundinamarca)                 1
Tibasosa (Boyacá)                    2
Tunja (Boyacá)                     171
Ventaquemada (Boyacá)                5
Villanueva (Casanare)                1
Villavicencio (Meta)                 1
Yopal (Casanare)                    21
Name: count, dtype: int64

# Conteo | P5- Género

In [295]:
# Conteo de respuestas en la columna 'P5-Género'
display(df_FlexDrive["P5-Género"].value_counts())

P5-Género
Femenino.             202
Masculino.            183
Prefiero no decir.      2
Name: count, dtype: int64

## Conteo | P6- Estrato socioeconómico

In [296]:
# Conteo de respuestas en la columna 'P6-Estrato'
display(df_FlexDrive["P6-Estrato"].value_counts())

P6-Estrato
3 - (Medio)           190
4 - (Medio Alto)       89
2 - (Bajo - Medio)     78
5 - (Alto)             15
1 - (Bajo)             12
6 - (Muy Alto)          3
Name: count, dtype: int64

## Limpieza y Conteo | P7 - Actividad Actual (Múltiple)

In [297]:
mapeo_ocupaciones = {
    "Concejal": ["Soy empleado"],
    "Empleada": ["Soy empleado"],
    "Empleado Publico": ["Soy empleado"],
    "Soy empleado comerciante": ["Soy empleado"],
    "Soy trabajador dependiente": ["Soy empleado"],
    
    "Consultor": ["Soy freelancer / independiente"],
    "Contratista": ["Soy freelancer / independiente"],
    "Independiente": ["Soy freelancer / independiente"],
    
    "Soy Aprendiz del SENA": ["Soy estudiante en estudios superiores o universitario"],
    
    "Hogar": ["Otro: Soy amo(a) de casa"],
    
    "Pensionado y independientemente": ["Estoy jubilado / pensionado / retirado",        "Soy freelancer / independiente"],
    
    "Empleado y estudiante universitario": ["Soy empleado",        "Soy estudiante en estudios superiores o universitario"],
}


# Aplicar el mapeo a la columna 'P7-Actividad_Actual_Multi'
df_FlexDrive = mapeo_respuestas(df_FlexDrive, "P7-Actividad_Actual_Multi", mapeo_ocupaciones)

# Conteo de respuestas (por agrupación) en la columna 'P7-Actividad_Actual_Multi'
display(df_FlexDrive["P7-Actividad_Actual_Multi"].value_counts())

# Conteo de respuestas (individuales) en la columna '
display(df_FlexDrive["P7-Actividad_Actual_Multi"].str.split(";").explode().value_counts())

P7-Actividad_Actual_Multi
Soy estudiante en estudios superiores o universitario                                                       167
Soy empleado                                                                                                 91
Soy freelancer / independiente                                                                               33
Soy estudiante de secundaria                                                                                 15
Soy estudiante en estudios superiores o universitario;Estoy desempleado                                      11
Soy estudiante en estudios superiores o universitario;Soy empleado                                           11
Estoy desempleado                                                                                             9
Soy empresario                                                                                                8
Soy estudiante en estudios superiores o universitario;Soy freelancer / independiente                          7
Estoy jubilado / pensionado / retirado                                                                        4
Soy empleado;Soy estudiante en estudios superiores o universitario                                            4
Soy estudiante de secundaria;Soy estudiante en estudios superiores o universitario                            4
Estoy desempleado;Soy estudiante en estudios superiores o universitario                                       3
Soy freelancer / independiente;Soy estudiante en estudios superiores o universitario                          3
Soy freelancer / independiente;Soy empleado                                                                   2
Soy estudiante de secundaria;Soy estudiante en estudios superiores o universitario;Soy empleado               2
Soy estudiante de secundaria;Soy empleado                                                                     2
Soy freelancer / independiente;Estoy desempleado                                                              1
Soy freelancer / independiente;Soy empleado;Estoy desempleado                                                 1
Otro: Soy amo(a) de casa                                                                                      1
Soy estudiante en estudios superiores o universitario;Soy empresario;Me encuentro en descanso / sabático      1
Soy empleado;Estoy jubilado / pensionado / retirado;Soy freelancer / independiente                            1
Soy estudiante en estudios superiores o universitario;Soy freelancer / independiente;Soy empresario           1
Estoy jubilado / pensionado / retirado;Soy freelancer / independiente                                         1
Me encuentro en descanso / sabático                                                                           1
Soy empleado;Estoy jubilado / pensionado / retirado                                                           1
Estoy jubilado / pensionado / retirado;Me encuentro en descanso / sabático                                    1
Soy freelancer / independiente;Soy empresario                                                                 1
Name: count, dtype: int64

P7-Actividad_Actual_Multi
Soy estudiante en estudios superiores o universitario    214
Soy empleado                                             115
Soy freelancer / independiente                            51
Estoy desempleado                                         25
Soy estudiante de secundaria                              23
Soy empresario                                            11
Estoy jubilado / pensionado / retirado                     8
Me encuentro en descanso / sabático                        3
Otro: Soy amo(a) de casa                                   1
Name: count, dtype: int64

# Conteo | P8- Nivel Educativo Alcanzado

In [298]:
# Conteo de respuestas en la columna 'P8-Nivel_Educativo'
display(df_FlexDrive["P8-Nivel_Educativo"].value_counts())

P8-Nivel_Educativo
Pregrado universitario (Grado o Licenciatura).                                                       196
Formación Técnica o Tecnológica.                                                                      59
Especialización o Diplomado de Posgrado (estudios posteriores con enfoque técnico o profesional).     59
Secundaria media (10° a 11°, o Vocacional, o Preparatoria).                                           44
Maestría (Estudios avanzados académicos o profesionales luego del posgrado).                          14
Secundaria básica (6° a 9°).                                                                           8
Primaria (1° a 5°).                                                                                    5
Doctorado (o PhD).                                                                                     2
Name: count, dtype: int64

# Conteo | P9- Frecuencia de uso: Servicios públicos de transporte

In [299]:
# Conteo de respuestas en la columna 'P9-Frecuencia_Uso_Servicios_Públicos'
display(df_FlexDrive["P9-Frecuencia_Uso_Servicios_Públicos"].value_counts())

P9-Frecuencia_Uso_Servicios_Públicos
Rara vez.                          146
Diariamente.                       130
Únicamente entre semana.            73
Únicamente los fines de semana.     35
En ninguna ocasión.                  3
Name: count, dtype: int64

In [300]:
df_FlexDrive[df_FlexDrive["P9-Frecuencia_Uso_Servicios_Públicos"] == "En ninguna ocasión."]

,Fecha_Presentación,Duración_mmss,P1-Autorización,P2-Edad,P3-País,P4-Ciudad,P5-Género,P6-Estrato,P7-Actividad_Actual_Multi,P8-Nivel_Educativo,P9-Frecuencia_Uso_Servicios_Públicos,P10-Servicios_Públicos_Usados_Multi,P11-Motivo_Desplazamiento_Multi,P12-Estado_Licencia_Conducción,P13-Posee_Veh_Propio,P14-Frecuencia_Uso_Veh[P13],P15-Cantidad_Veh_Propios[P13],P16-Modo_Uso_Veh[P15-U],P17-Tipo_Veh[P15-U],P18-Modo_Uso_Veh[P15-Multi],P19-Tipo_Veh[P15-Multi],P20-Conoce_P2P,P21-Beneficios_P2P,P22-Desventajas_P2P,P23-Ha_Rentado_Su_Veh,P24N-Forma_Renta[P21],P25N-Aspectos_Positivos_Exp[P21],P26N-Aspectos_Negativos_Exp2[P21],P27-Ha_Tomado_En_Renta,P28N-Lugar_donde_Rentó[P25],P29N-Entidades_Donde_Rentó[P25],P30N-Beneficios_Experiencia[P25],P31N-Desventajas_Experiencia[P25],P32-Interés_Propietario,P33-Modo_Preferido_Renta_Veh[P30],P34[A]-Prioridad:Seguro_Vehicular[P30],P34[B]-Prioridad:GPS_Vehicular[P30],P34[C]-Prioridad:Autentificar_Todos_Los_Users[P30],P34[D]-Prioridad:Seguridad_Pagos_Plataforma[P30],P34[E]-Prioridad:Comunicación_Directa_Cliente[P30],P34[F]-Prioridad:Apoyo_Precios[P30],P34[G]-Prioridad:Contratos_Automáticos[P30],P34[H]-Prioridad:Variedad_Pagos[P30],...,P34[K]-Prioridad:Asistencia_Legal[P30],P34[L]-Prioridad:Apoyo_Cómo_Cobrar[P30],P35N-Otras_Prioridades[P30],P36-Modelo_Confianza_Multi[P30],P37-Precio_Horas_Propietario_Multi[P30],P38_Precio_Dia_Propietario_Multi[P30],P39_Recibir_Pagos_Propietario[P30],P40[A]-Confianza:Edad_Experiencia_Cliente[P30],P40[B]-Confianza:Antecedentes_Cliente[P30],P40[C]-Confianza:Medio_Pago_Ofertado[P30],P40[D]-Confianza:Calificación_Que_Tiene_El_Cliente[P30],P40[E]-Confianza:Motivo_Solicitud[P30],P41N-Otros_Motivos_Para_Rentar_Seguro[P30],P42-Pago_FlexDrive_Propietarios[P30],P43-Interés_Cliente,P44-Modo_Preferido_Renta_Veh[P41],P45[A]-Prioridad:Comunicación_Propietario[P41],P45[B]-Prioridad:Facilidad_Variedad_Pagos[P41],P45[C]-Prioridad:Variedad_Seguros[P41],P45[D]-Prioridad:Verificación_Usuarios[P41],P45[E]-Prioridad:Apoyo_Dudas[P42],P45[F]-Prioridad:Precios_y_Ofertas[P41],P45[G]-Prioridad:Comunicación_FlexDrive[P41],P45[H]-Prioridad:Reseñar_Propietarios[P41],P45[I]-Prioridad:Modelo_Renta_en_15MINS[P41],P45[J]-Prioridad:Modelo_Negociación[P41],P46N-Otras_Prioridades_Para_Tomar_en_Renta[41],P47-Precio_Horas_Cliente_Multi[P41],P48-Precio_Dia_Cliente_Multi[P41],P49[A]-Confianza:Negociar_con_Propietario[P41],P49[B]-Confianza:Antigüedad_Veh[P41],P49[C]-Confianza:Medio_de_Pago_Recibido[P41],P49[D]-Confianza:Reseñas_Veh[P41],P49[E]-Confianza:Reseñas_Propietario[P41],P49[F]-Confianza:Claridad_Contrato[P41],P49[G]-Confianza:Punto_Entrega_Devolución_Vehículo[P41],P49[H]-Confianza:Revisión_Tecnicomecánica_Veh[P41],P50N-Otros_Puntos_Confianza_para_Rentar[P41],P51-¿Entiende_FlexDrive?,P52-¿Usaria_FlexDrive?,P53-Preferencias_para_Comunicarse_con_FlexDrive,Duración_Minutos,Duración_Rango
200,2025-05-20,07:47,Acepto.,18-25,Colombia,Tunja (Boyacá),Femenino.,3 - (Medio),Soy estudiante en estudios superiores o univer...,Pregrado universitario (Grado o Licenciatura).,En ninguna ocasión.,Taxis;Buses municipales;,Por estudio.;Por compromisos personales o fami...,"No poseo licencia, pero estoy interesado en ob...",Sí,Muy rara vez.,Un único vehículo.,"Sí, es un vehículo compartido con familiares, ...",Autobús,NaN,NaN,Sí,Mayor flexibilidad en horarios.;Mejor negociac...,Posibles daños o mal uso del vehículo rentado....,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,"No me llama la atención, gracias.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"¡Sí, me apuntaría en el presente o en el futuro!",Por horas.;Por días.;Por semanas.;,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,No aplica,Entre $15.000 a $30.000 la hora.;,Entre $150.000 a $200.000 el día.;,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🟡Prioridad Media🟡,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,No aplica,Clara,Muy probable - Me gustaría inscribirme en la p...,Un chat en la plataforma.;Por correo electróni...,7,"[6, 8)"
211,2025-05-20,02:51,Acepto.,18-25,Colombia,Tunja (Boyacá),Masculino.,5 - (Alto),Soy estudiante en estudios superiores o univer...,Pregrado universitario (Grado o Licenciatura).,En ninguna ocasión.,Metro;,Por compromisos personales o familiares.;,"No poseo licencia, y tampoco estoy interesado ...",No,NaN,NaN,NaN,NaN,NaN,NaN,No,Experiencia de negocio más personalizada.;,Falta de regulación por parte de entidades ofi...,Sí,A través de una empresa o entidad presencial.;,Buena gestión por parte de la entidad sobre el...,Inseguridad o falta de protección frente a dañ...,No,NaN,NaN,NaN,NaN,"No me llama la atención, gracias.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"¡Sí, me apuntaría en el presente o en el futuro!",Por meses.;,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🟡Prioridad Media🟡,NaN,Entre $50.000 a $80.000 la hora.;Desde $80.000...,Desde $350.000 en adelante.;Entre $200.000 a $...,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,NaN,Confusa,Probable - Me gustaría conocer más de la plata...,Por llamada telefónica.;,2,"[2, 4)"
230,2025-05-20,05:50,Acepto.,26-35,Colombia,NaN,Femenino.,3 - (Medio),Soy estudiante en estudios superiores o univer...,Maestría (Estudios avanzados académicos o prof...,En ninguna ocasión.,Carro;,Por trabajo.;Por estudio.;,Poseo licencia de conducción vigente o próxima...,Sí,Diariamente.,Un único vehículo.,"No, es un vehículo completamente propio.","Automóvil (carros, camionetas, entre otros)",NaN,NaN,Sí,Mejor negociación en condiciones de arriendo.;,Posibles daños o mal uso del vehículo rentado.;,Sí,A través de una plataforma web.;De forma indep...,Buen margen de ganancias.;Transparencia en las...,Inseguridad o falta de protección frente a dañ...,No,NaN,NaN,NaN,NaN,"No me llama la atención, gracias.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"No me llama la atención, gracias.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Clara,Neutral - Es un buen concepto que requiere más...,Un chat en la plataforma.;,5,"[4, 6)"

## Limpieza y Conteo | P10 - Servicios Públicos usados (Multi)

In [301]:
mapeo_servicios_publicos = {
    "Sistemas Integrados de Transporte Público [SITP] (Ej. Transmilenio, Metrolínea, Transcaribe, MIO, etc.)": ["SITP"],
    "Metro": ["SITP"],
    "Tele-cable": ["SITP"],
    "Transmilenio": ["SITP"],
    "Sistemas de interconexión": ["SITP"],
    
    "Ninguna en el momento": [],
    "Coontrasven": [],
    "Caminando": [],
    "Na": [],
    "Tengo carro": [],
    "bus": [],
    "Bicicleta": [],
    "Auto propio": [],
    "cicla": [],

    
    "Moto": ["Otro: Servicios (informales)"],
    "Carro": ["Otro: Servicios (informales)"],
    "Mototaxi": ["Otro: Servicios (informales)"],
    "Buses piratas": ["Otro: Servicios (informales)"],
    
    "Uber": ["Otro: Plataformas digitales de transporte (servicios privados)"],
    "plataformas": ["Otro: Plataformas digitales de transporte (servicios privados)"],
    "uber": ["Otro: Plataformas digitales de transporte (servicios privados)"],
    "Plataformas": ["Otro: Plataformas digitales de transporte (servicios privados)"],
    "IN DRIVER. PLATAFORMA": ["Otro: Plataformas digitales de transporte (servicios privados)"],
    "Drive": ["Otro: Plataformas digitales de transporte (servicios privados)"],
    "Indriver": ["Otro: Plataformas digitales de transporte (servicios privados)"],
    "Plataformas digitales de transporte": ["Otro: Plataformas digitales de transporte (servicios privados)"],
    "Uber o DiDi": ["Otro: Plataformas digitales de transporte (servicios privados)"],
    "Aplicaciones": ["Otro: Plataformas digitales de transporte (servicios privados)"],
}

# Aplicar el mapeo a la columna 'P10-Servicios_Públicos_Usados_Multi'
df_FlexDrive = mapeo_respuestas(df_FlexDrive, "P10-Servicios_Públicos_Usados_Multi", mapeo_servicios_publicos)

# Conteo de respuestas (por agrupación) en la columna 'P10-Servicios_Públicos_Usados_Multi'
display(df_FlexDrive["P10-Servicios_Públicos_Usados_Multi"].value_counts())

# Conteo de respuestas (individuales) en la columna 'P10-Servicios_Públicos_Usados_Multi'
display(df_FlexDrive["P10-Servicios_Públicos_Usados_Multi"].str.split(";").explode().value_counts())

P10-Servicios_Públicos_Usados_Multi
Buses municipales                                                                             80
Taxis                                                                                         51
Taxis;Buses municipales                                                                       43
Taxis;Buses municipales;Buses intermunicipales                                                34
Buses intermunicipales                                                                        22
Buses municipales;Taxis                                                                       20
SITP                                                                                          20
Buses municipales;Buses intermunicipales                                                      19
Taxis;Buses intermunicipales                                                                  10
Taxis;SITP                                                                                    10
Otro: Plataformas digitales de transporte (servicios privados)                                 8
                                                                                               7
Taxis;Buses municipales;Buses intermunicipales;SITP                                            6
Buses municipales;Taxis;Buses intermunicipales                                                 5
Buses municipales;SITP                                                                         5
Taxis;Buses intermunicipales;Buses municipales                                                 4
Otro: Servicios (informales)                                                                   4
Buses intermunicipales;Buses municipales                                                       4
Buses municipales;Buses intermunicipales;SITP                                                  4
Taxis;Otro: Plataformas digitales de transporte (servicios privados)                           3
Buses intermunicipales;SITP                                                                    3
Taxis;Buses intermunicipales;SITP                                                              2
Taxis;Buses municipales;Otro: Plataformas digitales de transporte (servicios privados)         2
SITP;Taxis                                                                                     2
Buses municipales;Buses intermunicipales;Taxis                                                 2
Buses intermunicipales;Buses municipales;Taxis                                                 2
Taxis;Buses municipales;SITP                                                                   2
SITP;Buses municipales                                                                         2
Taxis;SITP;Otro: Plataformas digitales de transporte (servicios privados)                      1
Buses municipales;Otro: Plataformas digitales de transporte (servicios privados)               1
Buses intermunicipales;Taxis;SITP                                                              1
Taxis;SITP;Buses municipales                                                                   1
Buses municipales;Taxis;Otro: Plataformas digitales de transporte (servicios privados)         1
Otro: Servicios (informales);Buses intermunicipales                                            1
Buses intermunicipales;Otro: Plataformas digitales de transporte (servicios privados)          1
Buses intermunicipales;SITP;Otro: Plataformas digitales de transporte (servicios privados)     1
Buses municipales;Buses intermunicipales;Taxis;SITP                                            1
Taxis;Buses intermunicipales;Buses municipales;SITP                                            1
Taxis;Otro: Servicios (informales)                                                             1
Name: count, dtype: int64

P10-Servicios_Públicos_Usados_Multi
Buses municipales                                                 239
Taxis                                                             205
Buses intermunicipales                                            123
SITP                                                               62
Otro: Plataformas digitales de transporte (servicios privados)     18
                                                                    7
Otro: Servicios (informales)                                        6
Name: count, dtype: int64

## Limpieza y Conteo | P11 - Motivos de Desplazamiento (Múltiple)

In [302]:
mapeo_motivos_desplazamiento = {
    "Si el carro tiene pico y placa o si está lloviendo": ["Otro: Por pico y placa o relacionados"],
    "Por pico y placa o normativa de tránsito" : ["Otro: Por pico y placa o relacionados"],
    
    "Llevar al trabajo a mi esposa": ["Por compromisos personales o familiares"],
    "Comida": ["Por compromisos personales o familiares"],
    "Citas medicas": ["Por compromisos personales o familiares"],
    "Entrenamientos": ["Por compromisos personales o familiares"],
    "Salud": ["Por compromisos personales o familiares"],
}

# Aplicar el mapeo a la columna 'P11-Motivo_Desplazamiento_Multi'
df_FlexDrive = mapeo_respuestas(df_FlexDrive, 'P11-Motivo_Desplazamiento_Multi', mapeo_motivos_desplazamiento)

# Conteo de respuestas (por agrupación) en la columna 'P11-Motivo_Desplazamiento_Multi'
display(df_FlexDrive["P11-Motivo_Desplazamiento_Multi"].value_counts())

# Conteo de respuestas (individuales) en la columna 'P11-Motivo_Desplazamiento_Multi'
display(df_FlexDrive["P11-Motivo_Desplazamiento_Multi"].str.split(";").explode().value_counts())

P11-Motivo_Desplazamiento_Multi
Por estudio                                                                    117
Por trabajo                                                                     81
Por compromisos personales o familiares                                         51
Por estudio;Por compromisos personales o familiares                             44
Por trabajo;Por compromisos personales o familiares                             25
Por estudio;Por trabajo                                                         11
Por trabajo;Por estudio                                                         10
Por compromisos personales o familiares;Por turismo                              7
Por compromisos personales o familiares;Por trabajo                              6
Por turismo                                                                      5
Por trabajo;Por estudio;Por compromisos personales o familiares                  4
Por estudio;Por trabajo;Por compromisos personales o familiares                  4
Por compromisos personales o familiares;Por estudio                              3
Por trabajo;Por compromisos personales o familiares;Por turismo                  3
Por estudio;Por compromisos personales o familiares;Por turismo                  3
Otro: Por pico y placa o relacionados                                            2
Por estudio;Por turismo                                                          2
Por trabajo;Por turismo                                                          2
Por estudio;Por turismo;Por compromisos personales o familiares                  1
Por trabajo;Por turismo;Por compromisos personales o familiares                  1
Por compromisos personales o familiares;Por trabajo;Por estudio                  1
Por estudio;Por compromisos personales o familiares;Por trabajo;Por turismo      1
Por compromisos personales o familiares;Por estudio;Por turismo                  1
Por compromisos personales o familiares;Por turismo;Por trabajo                  1
Por turismo;Por compromisos personales o familiares                              1
Name: count, dtype: int64

P11-Motivo_Desplazamiento_Multi
Por estudio                                202
Por compromisos personales o familiares    157
Por trabajo                                150
Por turismo                                 28
Otro: Por pico y placa o relacionados        2
Name: count, dtype: int64

## Limpieza y Conteo | P17 - Tipo de Vehículo Propio (Único)

In [303]:
mapeo_motivos_desplazamiento = {
    "Cicla": ["Otro: Bicicleta convencional"],
    "Bicicleta convencional": ["Otro: Bicicleta convencional"],
    "Moticicleta": ["Motocicleta"]
}

# Aplicar el mapeo a la columna 'P17-Tipo_Veh[P15-U]'
df_FlexDrive = mapeo_respuestas(df_FlexDrive, 'P17-Tipo_Veh[P15-U]', mapeo_motivos_desplazamiento)

# Mostrar las respuestas únicas en la columna 'P17-Tipo_Veh[P15-U]' luego del mapeo
df_FlexDrive['P17-Tipo_Veh[P15-U]'].str.split(";").explode().value_counts()

P17-Tipo_Veh[P15-U]
                                               268
Automóvil (carros, camionetas, entre otros)     88
Motocicleta                                     20
Autobús                                          3
Scooter                                          3
Otro: Bicicleta convencional                     2
Bicicleta eléctrica                              2
Camión                                           1
Name: count, dtype: int64

## Conteo | P18 - Uso de los Vehículos Propios (Múltiple)

In [304]:
# Conteo de respuestas (por agrupación) en la columna 'P18-Modo_Uso_Veh[P15-Multi]'
display(df_FlexDrive["P18-Modo_Uso_Veh[P15-Multi]"].value_counts())

# Conteo de respuestas (individuales) en la columna 'P18-Modo_Uso_Veh[P15-Multi]'
display(df_FlexDrive["P18-Modo_Uso_Veh[P15-Multi]"].str.split(";").explode().value_counts())

P18-Modo_Uso_Veh[P15-Multi]
Sí, comparto mi vehículo personal con familiares, amigos o conocidos.;                                                                     11
No, son vehículos completamente propios.;                                                                                                  10
Sí, ocasionalmente comparto otros vehículos con familiares, amigos, conocidos o por negocios.;                                              4
No, son vehículos completamente propios.;Sí, ocasionalmente comparto otros vehículos con familiares, amigos, conocidos o por negocios.;     1
Sí, comparto mi vehículo personal con familiares, amigos o conocidos.;No, son vehículos completamente propios.;                             1
Name: count, dtype: int64

P18-Modo_Uso_Veh[P15-Multi]
                                                                                                 27
Sí, comparto mi vehículo personal con familiares, amigos o conocidos.                            12
No, son vehículos completamente propios.                                                         12
Sí, ocasionalmente comparto otros vehículos con familiares, amigos, conocidos o por negocios.     5
Name: count, dtype: int64

## Conteo | P19 - Tipos de los Vehículos Propios (Múltiple)

In [305]:
# Conteo de respuestas (por agrupación) en la columna 'P19-Tipo_Veh[P15-Multi]'
display(df_FlexDrive["P19-Tipo_Veh[P15-Multi]"].value_counts())

# Conteo de respuestas (individuales) en la columna 'P19-Tipo_Veh[P15-Multi]'
display(df_FlexDrive["P19-Tipo_Veh[P15-Multi]"].str.split(";").explode().value_counts())

P19-Tipo_Veh[P15-Multi]
Automóvil (carros, camionetas, entre otros);                                    13
Moticicleta;Automóvil (carros, camionetas, entre otros);                         7
Scooter;                                                                         1
Scooter;Automóvil (carros, camionetas, entre otros);                             1
Moticicleta;                                                                     1
Automóvil (carros, camionetas, entre otros);Moticicleta;Bicicleta eléctrica;     1
Moticicleta;Automóvil (carros, camionetas, entre otros);Autobús;                 1
Automóvil (carros, camionetas, entre otros);Moticicleta;                         1
Tráiler;                                                                         1
Name: count, dtype: int64

P19-Tipo_Veh[P15-Multi]
                                               27
Automóvil (carros, camionetas, entre otros)    24
Moticicleta                                    11
Scooter                                         2
Bicicleta eléctrica                             1
Autobús                                         1
Tráiler                                         1
Name: count, dtype: int64

## Limpieza y Conteo | P21 - Beneficios P2P (Multi)
El presente cuenta con 3 casos para asignación de pesos:

- General (sin considerar "Otros: Acceso a un vehículo sin poseerlo")
- Con _Otros_ (considerando "Otros: Acceso a un vehículo sin poseerlo")
- Ninguno (0 absoluto en Interés)

In [306]:
#limpieza_preguntas_multi(df_FlexDrive, "P21-Beneficios_P2P")

mapeo_beneficios_P2P = {
    "No considero ninguno": [""],
    "Ninguno": [""],
    "Facilidad": [""],
    "Acceso a un vehículo sin poseerlo": ["Otros: Acceso a un vehículo sin poseerlo"],
}

# Aplicar el mapeo a la columna 'P21-Beneficios_P2P'
df_FlexDrive = mapeo_respuestas(df_FlexDrive, 'P21-Beneficios_P2P', mapeo_beneficios_P2P)

# Mostrar las respuestas únicas en la columna 'P21-Beneficios_P2P' luego del mapeo
df_FlexDrive['P21-Beneficios_P2P'].str.split(";").explode().value_counts()

P21-Beneficios_P2P
Posibilidad de generar ingresos como propietario del vehículo    163
Mayor flexibilidad en horarios                                   125
Aprovechamiento de vehículos particulares inactivos              108
Diversidad de vehículos para rentar / arrendar                   107
Promueve la economía colaborativa                                105
Mejor negociación en condiciones de arriendo                      76
                                                                  51
Experiencia de negocio más personalizada                          44
Otros: Acceso a un vehículo sin poseerlo                           1
Name: count, dtype: int64

## Limpieza y Conteo | P22 - Riesgos P2P (Multi)
El presente cuenta con 3 casos para asignación de pesos:

- General (sin considerar "Otros: Informalidad Laboral")
- Con _Otros_ (considerando "Otros: Informalidad Laboral")
- Ninguno (0 absoluto en Interés)

In [307]:
#limpieza_preguntas_multi(df_FlexDrive, "P22-Desventajas_P2P")

mapeo_desventajas_P2P = {
    "No considero ninguno": [""],
    "Ninguno": [""],
    "Informalidad laboral": ["Otros: Informalidad laboral"],
}

# Aplicar el mapeo a la columna 'P22-Desventajas_P2P'
df_FlexDrive = mapeo_respuestas(df_FlexDrive, 'P22-Desventajas_P2P', mapeo_desventajas_P2P)

# Mostrar las respuestas únicas en la columna 'P22-Desventajas_P2P' luego del mapeo
df_FlexDrive['P22-Desventajas_P2P'].str.split(";").explode().value_counts()

P22-Desventajas_P2P
Posibles daños o mal uso del vehículo rentado               261
Desconfianza frente a clientes / personas desconocidas      190
Posible uso de vehículos para fines no autorizados          165
Falta de regulación por parte de entidades oficiales        116
Falta de control en la entrega o devolución del vehículo    110
                                                             34
Otros: Informalidad laboral                                   1
Name: count, dtype: int64

## Limpieza y Conteo | P29N - Entidades donde han rentando otras personas (Abierta)

In [308]:
#limpieza_preguntas_multi(df_FlexDrive, "P29N-Entidades_Donde_Rentó[P25]")

mapeo_entidades_competencias_P29 = {
    "no": [""],
    "Ninguna": [""],
    "Fuera del pais": [""],
    "Con una empresa": [""],
    "No me acuerdo el nombre, fue en san Andrés, para recorrer una isla y en Ecuador": [""],
    "No recuerdo": [""],
    "En Norteamérica": [""],
    "No recuerdo nombre": [""],
    "Brasileñas y europeas": [""],
    "Renting": [""],
    
    "Rent car": ["Localiza"],
    "Rent a car": ["Localiza"],
    "Renta cars": ["Localiza"],
    "Rent car y otras": ["Localiza"],
    "Renta car y localiza": ["Localiza"],
    "SALE RENT A CAR, LOCALIZA": ["Localiza"],
    
    "HERZ,": ["Hertz"],
    "En estados unidos, tanto para viajar como para transporte dentro de ciudad, ambas ha sido mediante hertz": ["Hertz"],
    
    "Didi": ["DiDi"],
    "Uber, didi": ["Uber", "DiDi"],
    "Localiza, indriver, Uber": ["Localiza", "inDrive", "Uber"],
    
    "Yango- uber": ["Yango", "Uber"],
    
    "Por Facebook": ["Facebook Marketplace"],
}

# Aplicar el mapeo a la columna 'P29N-Entidades_Donde_Rentó[P25]'
df_FlexDrive = mapeo_respuestas(df_FlexDrive, 'P29N-Entidades_Donde_Rentó[P25]', mapeo_entidades_competencias_P29)

# Conteo de respuestas (por agrupación) en la columna 'P29N-Entidades_Donde_Rentó[P25]'
display(df_FlexDrive["P29N-Entidades_Donde_Rentó[P25]"].value_counts())

# Conteo de respuestas (individuales) en la columna 'P29N-Entidades_Donde_Rentó[P25]'
display(df_FlexDrive["P29N-Entidades_Donde_Rentó[P25]"].str.split(";").explode().value_counts())

P29N-Entidades_Donde_Rentó[P25]
                         361
Localiza                  10
Hertz                      3
DiDi                       2
Avis                       2
Yango;Uber                 1
Uber;DiDi                  1
Alamo                      1
Europcar                   1
Jkk                        1
Uber                       1
Turoll                     1
Localiza;inDrive;Uber      1
Facebook Marketplace       1
Name: count, dtype: int64

P29N-Entidades_Donde_Rentó[P25]
                        361
Localiza                 11
Uber                      4
DiDi                      3
Hertz                     3
Avis                      2
Yango                     1
Alamo                     1
Europcar                  1
Jkk                       1
Turoll                    1
inDrive                   1
Facebook Marketplace      1
Name: count, dtype: int64

## Limpieza y Conteo | P31 - Desventajas en entidades donde han rentado (Multi)

In [309]:
mapeo_desventajas_experiencias_P31N = {
    "Desproteccion legal ante un accidente": ["Otro: Protección legal nula ante incidentes"],
}

# Aplicar el mapeo a la columna 'P31N-Desventajas_Experiencia[P25]'
df_FlexDrive = mapeo_respuestas(df_FlexDrive, 'P31N-Desventajas_Experiencia[P25]', mapeo_desventajas_experiencias_P31N)

# Mostrar las respuestas únicas en la columna 'P31N-Desventajas_Experiencia[P25]' luego del mapeo
df_FlexDrive['P31N-Desventajas_Experiencia[P25]'].str.split(";").explode().value_counts()

P31N-Desventajas_Experiencia[P25]
                                                                     340
Costos elevados en comparación con lo esperado                        20
Lentitud en tiempos de atención y respuesta                           14
Información confusa sobre los contratos                               13
Dificultad para solicitar o acceder al servicio                       10
Poca o nula seguridad para accidentes o sin atención ante riesgos      7
Trato poco profesional o desinteresado                                 7
Falta de información en el servicio o vehículo a recibir               7
Dificultad al usar las tecnologías indicadas                           3
Otro: Protección legal nula ante incidentes                            1
Name: count, dtype: int64

# Codificación | P32- Interés Propietario

In [310]:
mapeo_interes_propietario_P32 = {
    "No me llama la atención, gracias": ["No"],
    "Sí, me llama la atención en el presente o futuro": ["Sí"],
}

df_FlexDrive = mapeo_respuestas(df_FlexDrive, 'P32-Interés_Propietario', mapeo_interes_propietario_P32)
df_FlexDrive["P32-Interés_Propietario"].value_counts()

P32-Interés_Propietario
No    222
Sí    165
Name: count, dtype: int64

## Conteo | P33- Modelo preferido para rentar para propietarios (Multi)

In [311]:
# Conteo de respuestas (por agrupación) en la columna 'P18-Modo_Uso_Veh[P15-Multi]'
display(df_FlexDrive["P33-Modo_Preferido_Renta_Veh[P30]"].value_counts())

# Conteo de respuestas (individuales) en la columna 'P33-Modo_Preferido_Renta_Veh[P30]'
display(df_FlexDrive["P33-Modo_Preferido_Renta_Veh[P30]"].str.split(";").explode().value_counts())

P33-Modo_Preferido_Renta_Veh[P30]
Por días (cualquier día).;                                                                                                        47
A disposición personal.;                                                                                                          25
Por horas.;                                                                                                                       25
Solo los fines de semana.;                                                                                                        17
Solo durante semana (lunes a viernes).;                                                                                           10
Por días (cualquier día).;A disposición personal.;                                                                                 7
Por horas.;Por días (cualquier día).;                                                                                              6
Por horas.;Por días (cualquier día).;Solo los fines de semana.;Solo durante semana (lunes a viernes).;A disposición personal.;     3
Por horas.;Por días (cualquier día).;Solo los fines de semana.;                                                                    3
Por días (cualquier día).;Por horas.;                                                                                              2
Por días (cualquier día).;Solo los fines de semana.;                                                                               2
A disposición personal.;Por días (cualquier día).;                                                                                 2
Por horas.;Por días (cualquier día).;Solo durante semana (lunes a viernes).;Solo los fines de semana.;A disposición personal.;     1
Por horas.;Solo los fines de semana.;Por días (cualquier día).;                                                                    1
Solo los fines de semana.;Por días (cualquier día).;                                                                               1
A disposición personal.;Solo durante semana (lunes a viernes).;                                                                    1
Por días (cualquier día).;Solo los fines de semana.;A disposición personal.;                                                       1
Solo los fines de semana.;Solo durante semana (lunes a viernes).;A disposición personal.;                                          1
Solo los fines de semana.;A disposición personal.;                                                                                 1
Por horas.;A disposición personal.;                                                                                                1
Por horas.;Solo los fines de semana.;                                                                                              1
Por días (cualquier día).;Solo los fines de semana.;Solo durante semana (lunes a viernes).;                                        1
Por horas.;Solo durante semana (lunes a viernes).;                                                                                 1
Solo durante semana (lunes a viernes).;Por horas.;Por días (cualquier día).;                                                       1
Por horas.;Por días (cualquier día).;A disposición personal.;                                                                      1
Solo durante semana (lunes a viernes).;A disposición personal.;                                                                    1
A disposición personal.;Por horas.;                                                                                                1
Por días (cualquier día).;Por horas.;Solo los fines de semana.;Solo durante semana (lunes a viernes).;                             1
Name: count, dtype: int64

P33-Modo_Preferido_Renta_Veh[P30]
                                          165
Por días (cualquier día).                  80
Por horas.                                 48
A disposición personal.                    46
Solo los fines de semana.                  34
Solo durante semana (lunes a viernes).     21
Name: count, dtype: int64

## Limpieza y Conteo | P35- Otras prioridades según propietarios (Abierta)

In [312]:
mapeo_otras_prioridades_propietarios_P35 = {
    '' : [""],
    '…' : [""],
    '.' : [""],
    '..' : [""],
    '...' : [""],
    'Sii' : [""],
    'Nose' : [""],
    'ñññññ' : [""],
    'Jtrujk' : [""],
    'Ninguna' : [""],
    'Ninguna' : [""],
    'Ninguna de' : [""],
    'UN CONTRATO' : [""],
    'Veliculo automático' : [""],
    'Mayor entrada económico' : [""],
    'Un vehículo en buen estado' : [""],
    'Confiabilidad en el cliente' : [""],
    'Que acepten pago en efectivo' : [""],
    'No tengo otras funcionalidades' : [""],
    
    'Póliza todo riesgo' : ["REVISAR 34A"],

    'Pagos seguros' : ["REVISAR 34D"],    
    
    'Antecedentes de la persona que renta el vehiculo' : ["REVISAR 40B"],
    'Seguridad al conocer quien es la persona que va a rentar mi carro.' : ["REVISAR 40B"],
    'Probablemente que a la persona que le rente mi vehículo no tenga antecedentes' : ["REVISAR 40B"],
    'La persona cuente con licencia de conducir y que no tenga problemas con la autoridad' : ["REVISAR 40B"],
    
    'Ayuda económica' : ["Otro: Incentivos económicos para el propietario"],
    
    
    'Seguros para los conductores' : ["Otro: Seguros para el conductor / arrendador"],
    'Seguro, en caso de cualquier siniestro o fatalidad' : ["Otro: Seguros para el conductor / arrendador"],
    
    'Multas o extra cobros por incumplimientos' : ["Otro: Apoyo legal por infracciones realizadas por el arrendador"],
    
    'Debería haber un seguro que cubra daños a personas o bienes causados por el vehículo, así mismo que cubra multas de tránsito.' : ["Otro: Apoyo legal por infracciones realizadas por el arrendador", 'Seguros para el conductor / arrendador'],
    
    'Confiabilidad' : ["Otro: Que el vehículo reciba un uso correcto"],
    'Tenerlo bonito' : ["Otro: Que el vehículo reciba un uso correcto"],
    'Seguridad del automóvil' : ["Otro: Que el vehículo reciba un uso correcto"],
    'El cuidado y el buen uso' : ["Otro: Que el vehículo reciba un uso correcto"],
    'Responsabilidad a la hora de utilizarlo' : ["Otro: Que el vehículo reciba un uso correcto"],
    'En si asegurar la integridad del vehículo' : ["Otro: Que el vehículo reciba un uso correcto"],
    'Método de registro del estado del vehículo antes y después de arrendarlo' : ["Otro: Que el vehículo reciba un uso correcto"],
    'Verificación de la responsabilidad del arrendador por el uso indebido del vehículo' : ["Otro: Que el vehículo reciba un uso correcto"],
    'Yo considero que una de las funcionalidades que haría que tenga más confianza a la hora de rentar mi vehículo, sería la protección continua tanto fuera como dentro del auto, y si llega haber algún fallo o accidente con el vehículo, el rentador tenga la responsabilidad de hacerce cargo de los daños pertinentes como rayones, golpes etc' : ["Otro: Que el vehículo reciba un uso correcto"],
    
    'Conductor elegido' : ["Otro: Definir quién será el conductor"],
    'Seguridad al conocer quien es la persona que va a rentar mi carro': ["Otro: Definir quién será el conductor"],
    
    'Elementos de seguridad vial y protección personal vigentes y buen estado' : ["Otro: Elementos de Seguridad Vial y Protección personal por parte del arrendador"],
}

# Generamos una columna limpia de ocupaciones
df_FlexDrive = mapeo_respuestas(df_FlexDrive, 'P35N-Otras_Prioridades[P30]', mapeo_otras_prioridades_propietarios_P35)

# Conteo de respuestas (por agrupación) en la columna 'P35N-Otras_Prioridades[P30]'
display(df_FlexDrive["P35N-Otras_Prioridades[P30]"].value_counts())

# Conteo de respuestas (individuales) en la columna 'P35N-Otras_Prioridades[P30]'
display(df_FlexDrive["P35N-Otras_Prioridades[P30]"].str.split(";").explode().value_counts())

P35N-Otras_Prioridades[P30]
                                                                                                          365
Otro: Que el vehículo reciba un uso correcto                                                                9
REVISAR 40B                                                                                                 4
Otro: Seguros para el conductor / arrendador                                                                2
Otro: Apoyo legal por infracciones realizadas por el arrendador;Seguros para el conductor / arrendador      1
Otro: Elementos de Seguridad Vial y Protección personal por parte del arrendador                            1
Otro: Apoyo legal por infracciones realizadas por el arrendador                                             1
Otro: Incentivos económicos para el propietario                                                             1
REVISAR 34D                                                                                                 1
Otro: Definir quién será el conductor                                                                       1
REVISAR 34A                                                                                                 1
Name: count, dtype: int64

P35N-Otras_Prioridades[P30]
                                                                                    365
Otro: Que el vehículo reciba un uso correcto                                          9
REVISAR 40B                                                                           4
Otro: Apoyo legal por infracciones realizadas por el arrendador                       2
Otro: Seguros para el conductor / arrendador                                          2
Seguros para el conductor / arrendador                                                1
Otro: Elementos de Seguridad Vial y Protección personal por parte del arrendador      1
Otro: Incentivos económicos para el propietario                                       1
REVISAR 34D                                                                           1
Otro: Definir quién será el conductor                                                 1
REVISAR 34A                                                                           1
Name: count, dtype: int64

## CONTEO | P36- ¿Cómo prefieren usar _Flex Drive_? (Multi)

In [313]:
# Conteo de respuestas (por agrupación) en la columna 'P36-Modelo_Confianza_Multi[P30]'
display(df_FlexDrive["P36-Modelo_Confianza_Multi[P30]"].value_counts())

# Conteo de respuestas (individuales) en la columna 'P36-Modelo_Confianza_Multi[P30]'
display(df_FlexDrive["P36-Modelo_Confianza_Multi[P30]"].str.split(";").explode().value_counts())

P36-Modelo_Confianza_Multi[P30]
Reciba solicitudes y pueda aceptarlas o denegarlas.;                                                                                                                                                                                                                        43
Pueda configurar qué tipo de solicitudes quiero recibir, para luego aceptarlas o denegarlas.;                                                                                                                                                                               31
Reciba solicitudes y pueda aceptarlas o denegarlas.;Pueda configurar qué tipo de solicitudes quiero recibir, para luego aceptarlas o denegarlas.;Pueda confiar en la plataforma para que me consulten, o ellos mismos acepten y denieguen un servicio que me solicitan.;    30
Pueda confiar en la plataforma para que me consulten, o ellos mismos acepten y denieguen un servicio que me solicitan.;                                                                                                                                                     24
Reciba solicitudes y pueda aceptarlas o denegarlas.;Pueda confiar en la plataforma para que me consulten, o ellos mismos acepten y denieguen un servicio que me solicitan.;                                                                                                 11
Reciba solicitudes y pueda aceptarlas o denegarlas.;Pueda configurar qué tipo de solicitudes quiero recibir, para luego aceptarlas o denegarlas.;                                                                                                                           11
Pueda configurar qué tipo de solicitudes quiero recibir, para luego aceptarlas o denegarlas.;Pueda confiar en la plataforma para que me consulten, o ellos mismos acepten y denieguen un servicio que me solicitan.;                                                         6
Pueda configurar qué tipo de solicitudes quiero recibir, para luego aceptarlas o denegarlas.;Reciba solicitudes y pueda aceptarlas o denegarlas.;                                                                                                                            2
Pueda configurar qué tipo de solicitudes quiero recibir, para luego aceptarlas o denegarlas.;Pueda confiar en la plataforma para que me consulten, o ellos mismos acepten y denieguen un servicio que me solicitan.;Reciba solicitudes y pueda aceptarlas o denegarlas.;     2
Reciba solicitudes y pueda aceptarlas o denegarlas.;Pueda confiar en la plataforma para que me consulten, o ellos mismos acepten y denieguen un servicio que me solicitan.;Pueda configurar qué tipo de solicitudes quiero recibir, para luego aceptarlas o denegarlas.;     2
Pueda confiar en la plataforma para que me consulten, o ellos mismos acepten y denieguen un servicio que me solicitan.;Pueda configurar qué tipo de solicitudes quiero recibir, para luego aceptarlas o denegarlas.;                                                         1
Pueda confiar en la plataforma para que me consulten, o ellos mismos acepten y denieguen un servicio que me solicitan.;Pueda configurar qué tipo de solicitudes quiero recibir, para luego aceptarlas o denegarlas.;Reciba solicitudes y pueda aceptarlas o denegarlas.;     1
Pueda confiar en la plataforma para que me consulten, o ellos mismos acepten y denieguen un servicio que me solicitan.;Reciba solicitudes y pueda aceptarlas o denegarlas.;                                                                                                  1
Name: count, dtype: int64

P36-Modelo_Confianza_Multi[P30]
                                                                                                                          165
Reciba solicitudes y pueda aceptarlas o denegarlas.                                                                       103
Pueda configurar qué tipo de solicitudes quiero recibir, para luego aceptarlas o denegarlas.                               86
Pueda confiar en la plataforma para que me consulten, o ellos mismos acepten y denieguen un servicio que me solicitan.     78
Name: count, dtype: int64

# Limpieza y Conteo | P39- ¿Cómo quieren recibir los propietarios el pago?
Caso especial ID = 149. Tiene vehículo, le interesaría poner en renta, pero luego dice que no quiere rentar su vehículo al momento de recibir los pagos (P39)

In [314]:
mapeo_recibir_pagos_propietarios_P39 = {
    'Me gustaría que el pago quedara de tal forma que cuando todo allá salido según lo previsto se pague o se devuelva el dinero' : [""],   #Debido a que contesta también otros puntos. Expresa solo intención
    'No rentaría mi vehiculo' : ["RESPUESTA INVÁLIDA - REVISAR"],
}

# Generamos una columna limpia de ocupaciones
df_FlexDrive = mapeo_respuestas(df_FlexDrive, 'P39_Recibir_Pagos_Propietario[P30]', mapeo_recibir_pagos_propietarios_P39)

# Conteo de respuestas (por agrupación) en la columna 'P39_Recibir_Pagos_Propietario[P30]'
display(df_FlexDrive["P39_Recibir_Pagos_Propietario[P30]"].value_counts())

# Conteo de respuestas (individuales) en la columna 'P39_Recibir_Pagos_Propietario[P30]'
display(df_FlexDrive["P39_Recibir_Pagos_Propietario[P30]"].str.split(";").explode().value_counts())

P39_Recibir_Pagos_Propietario[P30]
                                                                                                                                                                                                                                                                                                                                                                                  222
Por transacción bancaria inmediata, una vez aprobado el servicio por mí y el cliente                                                                                                                                                                                                                                                                                               40
En efectivo, antes de entregar el vehículo al cliente                                                                                                                                                                                                                                                                                                                              33
En efectivo, antes de entregar el vehículo al cliente;Por transacción bancaria inmediata, una vez aprobado el servicio por mí y el cliente                                                                                                                                                                                                                                         16
En efectivo, cuando el cliente devuelve el vehículo                                                                                                                                                                                                                                                                                                                                11
Por transacción bancaria inmediata, al finalizar el servicio                                                                                                                                                                                                                                                                                                                        9
Un respaldo con un pagaré automatizado por transferencia bancaria al finalizar el servicio por medio de Flex Drive                                                                                                                                                                                                                                                                  8
Por transacción bancaria inmediata, una vez aprobado el servicio por mí y el cliente;Un respaldo con un pagaré automatizado por transferencia bancaria al finalizar el servicio por medio de Flex Drive                                                                                                                                                                             6
En efectivo, antes de entregar el vehículo al cliente;Un respaldo con un pagaré automatizado por transferencia bancaria al finalizar el servicio por medio de Flex Drive                                                                                                                                                                                                            6
En efectivo, antes de entregar el vehículo al cliente;Por transacción bancaria inmediata, una vez aprobado el servicio por mí y el cliente;Un respaldo con un pagaré automatizado por transferencia bancaria al finalizar el servicio por medio de Flex Drive                                                                                                                       5
Por transacción bancaria inmediata, una vez aprobado el servicio por mí y el cliente;En efectivo, antes de entregar el vehículo al cliente                                                                                                                                                                                                                                          3
En efectivo, antes de entregar el vehículo al cliente;Por transacción bancaria inmediata, al finalizar el servicio;Un respaldo con un pagaré automatizado por transferencia bancaria al finalizar el servicio por medio de Flex Drive                                                                                                                                               2
En efectivo, cuando el cliente devuelve el vehículo;Por transacción bancaria inmediata, al finalizar el servicio;Por transacción bancaria inmediata, una vez aprobado el servicio por mí y el cliente                                                                                                                                                                               2
En efectivo, antes de entregar el vehículo al cliente;Por transacción bancaria inmediata, una vez aprobado el servicio por mí y el cliente;Por transacción bancaria inmediata, al finalizar el servicio                                                                                                                                                                             2
Un respaldo con un pagaré automatizado por transferencia bancaria al finalizar el servicio por medio de Flex Drive;En efectivo, antes de entregar el vehículo al cliente;Por transacción bancaria inmediata, una vez aprobado el servicio por mí y el cliente                                                                                                                       2
Un respaldo con un pagaré automatizado por transferencia bancaria al finalizar el servicio por medio de Flex Drive;Por transacción bancaria inmediata, una vez aprobado el servicio por mí y el cliente                                                                                                                                                                             2
RESPUESTA INVÁLIDA - REVISAR                                                                                                                                                                                                                                                                                                                                                        1
En efectivo, cuando el cliente devuelve el vehículo;Por transacción bancaria inmediata, al finalizar el servicio                                                                                                                                                                                                                                                                    1
Por transacción bancaria inmediata, una vez aprobado el servicio por mí y el cliente;En efectivo, antes de entregar el vehículo al cliente;En efectivo, cuando el cliente devuelve el vehículo                                                                                                                                                                                      1
Por transacción bancaria inmediata, al finalizar el servicio;Por transacción bancaria inmediata, una vez aprobado el servicio por mí y el cliente;En efectivo, antes de entregar el vehículo al cliente;En efectivo, cuando el cliente devuelve el vehículo                                                                                                                         1
En efectivo, cuando el cliente devuelve el vehículo;Por transacción bancaria inmediata, una vez aprobado el servicio por mí y el cliente                                                                                                                                                                                                                                            1
En efectivo, antes de entregar el vehículo al cliente;En efectivo, cuando el cliente devuelve el vehículo;Por transacción bancaria inmediata, una vez aprobado el servicio por mí y el cliente;Por transacción bancaria inmediata, al finalizar el servicio;Un respaldo con un pagaré automatizado por transferencia bancaria al finalizar el servicio por medio de Flex Drive      1
Un respaldo con un pagaré automatizado por transferencia bancaria al finalizar el servicio por medio de Flex Drive;Por transacción bancaria inmediata, una vez aprobado el servicio por mí y el cliente;En efectivo, antes de entregar el vehículo al cliente                                                                                                                       1
Por transacción bancaria inmediata, al finalizar el servicio;En efectivo, antes de entregar el vehículo al cliente;Por transacción bancaria inmediata, una vez aprobado el servicio por mí y el cliente;En efectivo, cuando el cliente devuelve el vehículo                                                                                                                         1
Por transacción bancaria inmediata, una vez aprobado el servicio por mí y el cliente;En efectivo, antes de entregar el vehículo al cliente;En efectivo, cuando el cliente devuelve el vehículo;Por transacción bancaria inmediata, al finalizar el servicio                                                                                                                         1
En efectivo, antes de entregar el vehículo al cliente;En efectivo, cuando el cliente devuelve el vehículo                                                                                                                                                                                                                                                                           1
Por transacción bancaria inmediata, una vez aprobado el servicio por mí y el cliente;Por transacción bancaria inmediata, al finalizar el servicio                                                                                                                                                                                                                                   1
Por transacción bancaria inmediata, una vez aprobado el servicio por mí y el cliente;En efectivo, antes de entregar el vehículo al cliente;Por transacción bancaria inmediata, al finalizar el servicio                                                                                                                                                                             1
En efectivo, antes de entregar el vehículo al cliente;En efectivo, cuando el cliente devuelve el vehículo;Por transacción bancaria inmediata, una vez aprobado el servicio por mí y el cliente                                                                                                                                                                                      1
Por transacción bancaria inmediata, al finalizar el servicio;Por transacción bancaria inmediata, una vez aprobado el servicio por mí y el cliente                                                                                                                                                                                                                                   1
Por transacción bancaria inmediata, una vez aprobado el servicio por mí y el cliente;En efectivo, antes de entregar el vehículo al cliente;Un respaldo con un pagaré automatizado por transferencia bancaria al finalizar el servicio por medio de Flex Drive                                                                                                                       1
Por transacción bancaria inmediata, al finalizar el servicio;Por transacción bancaria inmediata, una vez aprobado el servicio por mí y el cliente;En efectivo, cuando el cliente devuelve el vehículo                                                                                                                                                                               1
Un respaldo con un pagaré automatizado por transferencia bancaria al finalizar el servicio por medio de Flex Drive;En efectivo, antes de entregar el vehículo al cliente                                                                                                                                                                                                            1
Por transacción bancaria inmediata, una vez aprobado el servicio por mí y el cliente;Por transacción bancaria inmediata, al finalizar el servicio;Un respaldo con un pagaré automatizado por transferencia bancaria al finalizar el servicio por medio de Flex Drive                                                                                                                1
Name: count, dtype: int64

P39_Recibir_Pagos_Propietario[P30]
                                                                                                                      222
Por transacción bancaria inmediata, una vez aprobado el servicio por mí y el cliente                                   92
En efectivo, antes de entregar el vehículo al cliente                                                                  80
Un respaldo con un pagaré automatizado por transferencia bancaria al finalizar el servicio por medio de Flex Drive     36
Por transacción bancaria inmediata, al finalizar el servicio                                                           25
En efectivo, cuando el cliente devuelve el vehículo                                                                    23
RESPUESTA INVÁLIDA - REVISAR                                                                                            1
Name: count, dtype: int64

## Limpieza y Conteo | P41N- Otros motivos para poder rentar seguro (propietarios) [Abierta]

In [315]:
mapeo_P41N_motivos_para_rentar_seguro = {
    'Seguro todo riesgo obligatorio para todos los vehiculo' : ["Obligatoriedad del Seguro todo riesgo (lo paga el arrendador)"],
    
    'La ubicación de mi carro': ["Revisar 34B"],
    'Que trayecto recorrerá con el automóvil': ["Revisar 34B"],
    
    'Dirección y antecedentes': ["Revisar 40B"],
    'Certificaciones de antecedentes judiciales': ["Revisar 40B"],
    'Antecedentes penales': ["Revisar 40B"],
    
    'La zona donde será utilizado': ["Revisar 40E"],
    
    'La plataforma debe ser confiable en el seguimiento a conductores y vehículos. Para esto debe responder a los dos usuarios de forma eficiente': ["Trazabilidad del servicio de arrendamiento"],
    
    '.': [""],
    'Nose': [""],
    'Njij': [""],
    '...': [""],
    'Creo que cubre todo ya al realizar todas estas preguntas': [""],
    '..': [""],
    'Ggg': [""],
    'si': [""],
    'Sii': [""],
    'Tidas las anteriores': [""],
    'Confiabilidad en el cliente': [""],
    'Cumplimiento': [""],
    'Honestidad y responsabilidad': [""],
    'ninguno': [""],
    'Ninguna': [""],
}

# Generamos una columna limpia de ocupaciones
df_FlexDrive = mapeo_respuestas(df_FlexDrive, 'P41N-Otros_Motivos_Para_Rentar_Seguro[P30]', mapeo_P41N_motivos_para_rentar_seguro)

# Conteo de respuestas (por agrupación) en la columna 'P41N-Otros_Motivos_Para_Rentar_Seguro[P30]'
display(df_FlexDrive["P41N-Otros_Motivos_Para_Rentar_Seguro[P30]"].value_counts())

P41N-Otros_Motivos_Para_Rentar_Seguro[P30]
                                                                 378
Revisar 40B                                                        3
Revisar 34B                                                        2
Trazabilidad del servicio de arrendamiento                         1
Revisar 40E                                                        1
Obligatoriedad del Seguro todo riesgo (lo paga el arrendador)      1
El clima                                                           1
Name: count, dtype: int64

## Limpieza y Conteo | P46- Otras funcionalidades de Flex Drive para clientes [Abierta]

In [316]:
mapeo_P46N_otras_funcionalidades_clientes = {
    'La coherencia entre el precio de alquiler y em vehículo' : ["Otro: Coherencia precio-servicio"],
    
    'Comunicación eficaz' : ["Revisar 45A", "Revisar 45G"],
    'Comunicación eficaz.' : ["Revisar 45A", "Revisar 45G"],
    
    'PODER ESCOGER EL VEHICULO APROPIADO' : ["Revisar 45F"],
    
    'La correcta regulación de los contratos de arrendamiento' : ["Revisar 49F"],
    
    'Lugares de entrega del vehículo' : ["Revisar 49G"],
    'Estado del vehículo, validación mecánica antes de alquilarlo' : ["Revisar 49G"],
    
    'Óptimo estado de los vehículos' : ["Revisar 49H"],
    'Que este en buen estado' : ["Revisar 49H"],
    'Que el carro este al día y en buen estado' : ["Revisar 49H"],
    'Condiciones del vehículo y estrellas de seguridad' : ["Revisar 49H"],
    'Documentos al día' : ["Revisar 49H"],
    'Conocer si el carro del arrendatario tiene todo en regla y el arrendado también' : ["Revisar 49H"],
    'el estado' : ["Revisar 49H"],
    
    'Además de la verificación de usuarios, debería haber un apartado de verificación de los vehículos, por placa, improntas, tarjeta de propiedad del vehículo o cualquier medio de verificación para saber que el auto es verdaderamente el que se ofrece en la página, para asegurarse de que no sea un auto robado o con otras placas, además de los documentos del vehículo al día ya que si la persona que conduce aunque no sea el dueño recibe un comparendo sea por SOAT, tecnomecánica o no tener el kit de carretera en regla u otro, si bien llegaría al propietario, este puede pasar a la autoridad un documento de cambio de infractor a la autoridad y además muchas de estas conllevan la inmovilización del vehículo' : ["Revisar 49H", "Otro: Logística de Apoyo Legal para infracciones"],
    
    'No aplica' : [""],
    'Ninguna' : [""],
    '...' : [""],
    '..' : [""],
    '.' : [""],
    'No se' : [""],
    'Conocer todos los aspectos ' : [""],
    'Ninguna todas están bien describidas' : [""],
    'Ninguna otra' : [""],
    'Sii' : [""],
    'Que este en muy buen estado' : [""],
    'muchas cosas' : [""],
    'Conocer todos los aspectos' : [""],
    'Seguridad' : [""],
    'Características del vehículo' : [""],
    'El modelo del vehículo y el kilometraje recorrido' : [""],
    'Que sean camionetas con alto cilindraje que pasen por trochas,' : [""],
    'Sería bueno como para transportar niños de los colegios' : [""],
    'El clima' : [""],
}

# Mapeamos las respuestas en la columna 'P46N-Otras_Prioridades_Para_Tomar_en_Renta'
df_FlexDrive = mapeo_respuestas(df_FlexDrive, 'P46N-Otras_Prioridades_Para_Tomar_en_Renta[41]', mapeo_P46N_otras_funcionalidades_clientes)


# Conteo de respuestas (por agrupación) en la columna 'P46N-Otras_Prioridades_Para_Tomar_en_Renta]'
display(df_FlexDrive["P46N-Otras_Prioridades_Para_Tomar_en_Renta[41]"].value_counts())


# Conteo de respuestas (individuales) en la columna 'P46N-Otras_Prioridades_Para_Tomar_en_Renta'
display(df_FlexDrive["P46N-Otras_Prioridades_Para_Tomar_en_Renta[41]"].str.split(";").explode().value_counts())

df_FlexDrive[df_FlexDrive["P46N-Otras_Prioridades_Para_Tomar_en_Renta[41]"].str.contains("Revisar")]

P46N-Otras_Prioridades_Para_Tomar_en_Renta[41]
                                                                373
Revisar 49H                                                       7
Revisar 49G                                                       2
Otro: Coherencia precio-servicio                                  1
Revisar 49H;Otro: Logística de Apoyo Legal para infracciones      1
Revisar 45F                                                       1
Revisar 49F                                                       1
Revisar 45A;Revisar 45G                                           1
Name: count, dtype: int64

P46N-Otras_Prioridades_Para_Tomar_en_Renta[41]
                                                    373
Revisar 49H                                           8
Revisar 49G                                           2
Otro: Coherencia precio-servicio                      1
Otro: Logística de Apoyo Legal para infracciones      1
Revisar 45F                                           1
Revisar 49F                                           1
Revisar 45A                                           1
Revisar 45G                                           1
Name: count, dtype: int64

,Fecha_Presentación,Duración_mmss,P1-Autorización,P2-Edad,P3-País,P4-Ciudad,P5-Género,P6-Estrato,P7-Actividad_Actual_Multi,P8-Nivel_Educativo,P9-Frecuencia_Uso_Servicios_Públicos,P10-Servicios_Públicos_Usados_Multi,P11-Motivo_Desplazamiento_Multi,P12-Estado_Licencia_Conducción,P13-Posee_Veh_Propio,P14-Frecuencia_Uso_Veh[P13],P15-Cantidad_Veh_Propios[P13],P16-Modo_Uso_Veh[P15-U],P17-Tipo_Veh[P15-U],P18-Modo_Uso_Veh[P15-Multi],P19-Tipo_Veh[P15-Multi],P20-Conoce_P2P,P21-Beneficios_P2P,P22-Desventajas_P2P,P23-Ha_Rentado_Su_Veh,P24N-Forma_Renta[P21],P25N-Aspectos_Positivos_Exp[P21],P26N-Aspectos_Negativos_Exp2[P21],P27-Ha_Tomado_En_Renta,P28N-Lugar_donde_Rentó[P25],P29N-Entidades_Donde_Rentó[P25],P30N-Beneficios_Experiencia[P25],P31N-Desventajas_Experiencia[P25],P32-Interés_Propietario,P33-Modo_Preferido_Renta_Veh[P30],P34[A]-Prioridad:Seguro_Vehicular[P30],P34[B]-Prioridad:GPS_Vehicular[P30],P34[C]-Prioridad:Autentificar_Todos_Los_Users[P30],P34[D]-Prioridad:Seguridad_Pagos_Plataforma[P30],P34[E]-Prioridad:Comunicación_Directa_Cliente[P30],P34[F]-Prioridad:Apoyo_Precios[P30],P34[G]-Prioridad:Contratos_Automáticos[P30],P34[H]-Prioridad:Variedad_Pagos[P30],...,P34[K]-Prioridad:Asistencia_Legal[P30],P34[L]-Prioridad:Apoyo_Cómo_Cobrar[P30],P35N-Otras_Prioridades[P30],P36-Modelo_Confianza_Multi[P30],P37-Precio_Horas_Propietario_Multi[P30],P38_Precio_Dia_Propietario_Multi[P30],P39_Recibir_Pagos_Propietario[P30],P40[A]-Confianza:Edad_Experiencia_Cliente[P30],P40[B]-Confianza:Antecedentes_Cliente[P30],P40[C]-Confianza:Medio_Pago_Ofertado[P30],P40[D]-Confianza:Calificación_Que_Tiene_El_Cliente[P30],P40[E]-Confianza:Motivo_Solicitud[P30],P41N-Otros_Motivos_Para_Rentar_Seguro[P30],P42-Pago_FlexDrive_Propietarios[P30],P43-Interés_Cliente,P44-Modo_Preferido_Renta_Veh[P41],P45[A]-Prioridad:Comunicación_Propietario[P41],P45[B]-Prioridad:Facilidad_Variedad_Pagos[P41],P45[C]-Prioridad:Variedad_Seguros[P41],P45[D]-Prioridad:Verificación_Usuarios[P41],P45[E]-Prioridad:Apoyo_Dudas[P42],P45[F]-Prioridad:Precios_y_Ofertas[P41],P45[G]-Prioridad:Comunicación_FlexDrive[P41],P45[H]-Prioridad:Reseñar_Propietarios[P41],P45[I]-Prioridad:Modelo_Renta_en_15MINS[P41],P45[J]-Prioridad:Modelo_Negociación[P41],P46N-Otras_Prioridades_Para_Tomar_en_Renta[41],P47-Precio_Horas_Cliente_Multi[P41],P48-Precio_Dia_Cliente_Multi[P41],P49[A]-Confianza:Negociar_con_Propietario[P41],P49[B]-Confianza:Antigüedad_Veh[P41],P49[C]-Confianza:Medio_de_Pago_Recibido[P41],P49[D]-Confianza:Reseñas_Veh[P41],P49[E]-Confianza:Reseñas_Propietario[P41],P49[F]-Confianza:Claridad_Contrato[P41],P49[G]-Confianza:Punto_Entrega_Devolución_Vehículo[P41],P49[H]-Confianza:Revisión_Tecnicomecánica_Veh[P41],P50N-Otros_Puntos_Confianza_para_Rentar[P41],P51-¿Entiende_FlexDrive?,P52-¿Usaria_FlexDrive?,P53-Preferencias_para_Comunicarse_con_FlexDrive,Duración_Minutos,Duración_Rango
53,2025-05-04,33:17,Acepto.,18-25,Colombia,Tunja (Boyacá),Masculino.,3 - (Medio),Soy estudiante en estudios superiores o univer...,Pregrado universitario (Grado o Licenciatura).,Diariamente.,Taxis;Buses municipales;Otro: Plataformas digi...,Por estudio,Poseo licencia de conducción vigente o próxima...,Sí,Diariamente.,Un único vehículo.,"Ocasionalmente lo comparto con mi familia, ami...","Automóvil (carros, camionetas, entre otros)",NaN,NaN,Sí,Posibilidad de generar ingresos como propietar...,Posibles daños o mal uso del vehículo rentado;...,No,NaN,NaN,NaN,No,NaN,,NaN,,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,,NaN,"¡Sí, me apuntaría en el presente o en el futuro!",Por horas.;Por días.;Por semanas.;,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🟡Prioridad Media🟡,Revisar 49H;Otro: Logística de Apoyo Legal par...,Entre $30.000 a $50.000 la hora.;,Entre $150.000 a $200.000 el día.;,🟢Prioridad Baja🟢,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,"Especificaciones en el nivel de gasolina, por ...",Clara,Neutral - Es un buen concepto que requiere más...,Un chat en la plataforma.;Por chat con asesor ...,33,"[32, 34)"
60,2025-05-05,17:45,Acepto.,46-55,Colombia,Yopal (Casanare),Masculino.,4 - (Medio Alto),Soy empresario,Especialización o Diplomado de Posgrado (estud...,Rara vez.,Taxis;SITP,Por compromisos personales o familiares;Por tr...,Poseo licencia de conducción vigente o próxima...,Sí,Diariamente.,Un único vehículo.,"Ocasionalmente lo comparto con mi familia, ami...","Automóvil (carros, camionetas, entre otros)",NaN,NaN,No,Aprovechamiento de vehículos particulares inac...,Desconfianza frente a clientes / personas desc...,No,NaN,NaN,NaN,Sí,NaN,Hertz,Tecnología fácil de utilizar (a través de plat...,Información confusa sobre los contratos;Poca o...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,,NaN,"¡Sí, me apuntaría en el presente o en el futuro!",Por días.;,🟡Prioridad Media🟡,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🟡Prioridad Media🟡,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🟡Prioridad Media🟡,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,Revisar 45F,Entre $30.000 a $50.000 la hora.;,Entre $150.000 a $200.000 el día.;,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,AGILIDAD EN LA RENTA,Clara,Probable - Me gustaría conocer más de la plata...,Un chat en la plataforma.;Por llamada telefóni...,17,"[16, 18)"
153,2025-05-18,10:11,Acepto.,56-65,Colombia,Sogamoso (Boyacá),Femenino.,2 - (Bajo - Medio),Soy empleado,Formación Técnica o Tecnológica.,Diariamente.,Buses municipales,Por trabajo,"No poseo licencia, pero estoy interesado en ob...",No,NaN,NaN,NaN,,NaN,NaN,Sí,Mayor flexibilidad en horarios,Posibles daños o mal uso del vehículo rentado,No,NaN,NaN,NaN,No,NaN,,NaN,,Sí,Por días (cualquier día).;,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,...,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,,Pueda confiar en la plataforma para que me con...,No me encuentro interesado en rentar por horas.;,Entre $100.000 a $150.000 el día.;,Un respaldo con un pagaré automatizado por tra...,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,,No estaría interesado en pagar comisión alguna.;,"¡Sí, me apuntaría en el presente o en el futuro!",Por días.;,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,Revisar 49H,Entre $15.000 a $30.000 la hora.;,Entre $100.000 a $150.000 el día.;,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,NaN,Clara,Muy probable - Me gustaría inscribirme en la p...,Un chat en la plataforma.;,10,"[10, 12)"
161,2025-05-18,12:26,Acepto.,18-25,Colombia,Tenjo (Cundinamarca),Femenino.,3 - (Medio),Soy estudiante en estudios superiores o univer...,Pregrado universitario (Grado o Licenciatura).,Únicamente entre semana.,Buses municipales,Por estudio,Poseo licencia de conducción vigente o próxima...,No,NaN,NaN,NaN,,NaN,NaN,Sí,Mejor negociación en condiciones de arriendo;D...,Posibles daños o mal uso del vehículo rentado;...,No,NaN,NaN,NaN,No,NaN,,NaN,,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,,NaN,"¡Sí, me apuntaría en el presente o en el futuro!",Por días.;,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🟡Prioridad Media🟡,🟡Prioridad Media🟡,Revisar 49G,Entre $30.000 a $50.000 la hora.;,Entre $200.000 a $250.000 el día.;,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,NaN,Clara,Probable - Me gustaría conocer más de la plata...,Un chat en la plataforma.;Por chat con asesor ...,12,"[12, 14)"
185,2025-05-19,08:43,Acepto.,18-25,Colombia,Tunja (Boyacá),Masculino.,4 - (Medio Alto),Soy estudiante en estudios superiores o univer...,Pregrado universitario (Grado o Licenciatura).,Únicamente los fines de semana.,Taxis;Buses municipales,Por trabajo;Por compromisos personales o famil...,Poseo licencia de conducción vigente o próxima...,No,NaN,NaN,NaN,,NaN,NaN,No,,Posibles daños o mal uso del vehículo rentado;...,No,NaN,NaN,NaN,No,NaN,,NaN,,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,,NaN,"¡Sí, me apuntaría en el presente o en el futuro!",Por días.;,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🟡Prioridad Media🟡,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,Revisar 49H,No me encuentro interesado en rentar por horas.;,Entre $100.000 a $150.000 el día.;Entre $150.0...,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,Si lo entregan tanqueado o no,Clara,Neutral - Es un buen concepto que requiere más...,Por correo electrónico.;Por chat con asesor me...,8,"[8, 10)"
223,2025-05-20,12:13,Acepto.,18-25,Colombia,Chía (Cundinamarca),Masculino.,4 - (Medio Alto),Soy estudiante en estudios superiores o univer...,Pregrado universitario (Grado o Licenciatura).,Diariamente.,Buses municipales;Buses intermunicipales,Por estudio;Por compromisos personales o famil...,Poseo licencia de conducción vigente o próxima...,No,NaN,NaN,NaN,,NaN,NaN,No,,Posibles daños o mal uso del vehículo rentado;...,No,NaN,NaN,NaN,Sí,En el exterior,Hertz,Facilidad en el acceso al servicio.;Acompañami...,Trato poco profesional o desinteresado;Informa...,Sí,Por días (cualquier día).;,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,...,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,Otro: Seguros para el conductor / arrendador,Reciba solicitudes y pueda aceptarlas o denega...,Entre $15.000 a $30.000 la hora.;,Entre $100.000 a $150.000 el día.;,"Por transacción bancaria inmediata, una vez ap...",🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,,Aceptaría pagar una comisión del 4% al 9% por ...,"¡Sí, me apuntaría en el presente o en el futuro!",Por días.;,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,NaN,Revisar 49H,Entre $15.000 a $30.000 la hora.;,Entre $100.000 a $150.000 el día.;,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,NaN,Clara,Probable - Me gustaría conocer más de la plata...,Por chat con asesor mediante Whatsapp.;,12,"[12, 14)"
245,2025-05-21,09:07,Acepto.,26-35,Colombia,Funza (Cundinamarca),Femenino.,2 - (Bajo - Medio),Soy empleado;Soy estudiante en estudios superi...,Formación Técnica o Tecnológica.,Rara vez.,,Por trabajo,"No poseo licencia, y tampoco estoy interesado ...",Sí,Diariamente.,Un único vehículo.,"No, es un vehículo completamente propio.",Otro: Bicicleta convencional,NaN,NaN,Sí,Mayor flexibilidad en horarios;Mejor negociaci...,Posibles daños o mal uso del vehículo rentado;...,No,NaN,NaN,NaN,No,NaN,,NaN,,Sí,Solo durante semana (lunes a viernes).;,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,...,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,Otro: Elementos de Seguridad Vial y Protección...,Reciba solicitudes y pueda aceptarlas o denega...,Entre $30.000 a $50.000 la hora.;,Entre $100.000 a $150.000 el día.;Entre $150.0...,"Por transacción bancaria inmediata, una vez ap...",🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,Revisar 40B,Preferiría pagar una suscripción mensual.;,"¡Sí, me apuntaría en el presente o en el futuro!",Por días.;Por semanas.;,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,Revisar 49G,Entre $15.000 a $30.000 la hora.;Entre $30.000...,Entre $100.000 a $150.000 el día.;Entre $150.0...,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,Estado de espejos y direccionales,Clara,Muy probable - Me gustaría inscribirme en la p...,Un chat en la plataforma.;Por correo electróni...,9,"[8, 10)"
278,2025-05-22,11:10,Acepto.,18-25,Colombia,Tunja (Boyacá),Masculino.,3 - (Medio),Soy estudiante en estudios superiores o univer...,Pregrado universitario (Grado o Licenciatura).,Rara vez.,Buses intermunicipales,Por estudio,Poseo licencia de conducción vigente o próxima...,No,NaN,NaN,NaN,,NaN,NaN,No,Posibilidad de generar ingresos como propietar...,Posibles daños o mal uso del vehículo rentado;...,No,NaN,NaN,NaN,No,NaN,,NaN,,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,,NaN,"¡Sí, me apuntaría en el presente o en el futuro!",Por semanas.;,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,Revisar 49F,Entre $15.000 a $30.000 la hora.;,Entre $150.000 a $200.000 el día.;,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,NaN,Clara,Probable - Me gustaría conocer más de la plata...,Por chat con asesor mediante Whatsapp.;Con un ...,11,"[10, 12)"
305,2025-05-22,08:33,Acepto.,18-25,Colombia,Tunja (Boyacá),Masculino.,4 - (Medio Alto),Soy estudiante en estudios superiores o univer...,Pregrado universitario (Grado o Licenciatura).,Únicamente entre semana.,Taxis;Buses intermunicipales;Buses municipales,Por estudio;Por compromisos personales o famil...,Poseo licencia de conducción vigente o próxima...,No,NaN,NaN,NaN,,NaN,NaN,Sí,Mayor flexibilidad en horarios;Diversidad de v...,Posibles daños o mal uso del vehículo rentado;...,Sí,A través de una empresa o entidad presencial.;...,Buen margen de ganancias.;Control sobre las de...,Decisiones arbitrarias por parte de la entidad...,Sí,Tanto en Colombia como en el exterior,Localiza,Rapidez en los tiempos de respuesta.;Transpare...,Lentitud en tiempos de atención y respuesta;In...,Sí,Por días (cualquier día).;,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🟡Prioridad Media🟡,🟢Prioridad Baja🟢,...,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,,Pueda confiar en la plataforma para que me con...,Entre $30.000 a $50.000 la hora.;Entre $15.000...,Entre $150.000 a $200.000 el día.;,"En efectivo, antes de entregar el vehículo al ...",🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,,Preferiría pagar una suscripción mensual.;,"¡Sí, me apuntaría en el presente o en el futuro!",Por días.;,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,Revisar 45A;Revisar 45G,Entre $15.000 a $30.000 la hora.;,Entre $100.000 a $150.000 el día.;,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,…,Clara,Muy probable - Me gustaría inscribirme en la p...,Por correo electrónico.;,8,"[8, 10)"
325,2025-05-23,19:17,Acepto.,18-25,Colombia,Tunja (Boyacá),Masculino.,3 - (Medio),Soy estudiante en estudios superiores o univer...,Pregrado universitario (Grado o Licenciatura).,Únicamente entre semana.,Taxis,Por estudio;Por trabajo,"No poseo licencia, pero estoy interesado en ob...",Sí,Solo durante fines de semana.,Un único vehículo.,"Ocasionalmente lo comparto con mi familia, ami...",Scooter,NaN,NaN,Sí,Posibilidad de generar ingresos como propietar...,Posibles daños o mal uso del vehículo rentado;...,No,NaN,NaN,NaN,Sí,Tanto en Colombia como en el exterior,,Facilidad en el acceso al servicio.;Rapidez en...,Dificultad para solicitar o acceder al servici...,Sí,Por días (cualquier día).;Solo los fines de se...,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,...,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,Otro: Que el vehículo reciba un uso correcto,Reciba solicitudes y pueda aceptarlas o denega...,Entre $15.000 a $30.000 la hora.;Entre $30.000...,Entre $100.000 a $150.000 el día.;Entre $150.0...,"En efectivo, antes de entregar el vehículo al ...",🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,,Aceptaría pagar una comisión del 4% al 9% por ...,"¡Sí, me apuntaría en el presente o en el futuro!",Por horas.;Por días.;Por semanas.;,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,Revisar 49H,Entre $15.000 a $30.000 la hora.;Entre $30.000...,Entre $100.000 a $150.000 el día.;Entre $150.0...,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,estado del vehículo,Clara,Muy probable - Me gustaría inscribirme en la p...,Un chat en la plataforma.;,19,"[18, 20)"
335,2025-05-23,19:39,Acepto.,66-75,Colombia,Santa Rosa De Viterbo (Boyacá),Masculino.,3 - (Medio),Soy empleado,"Secundaria media (10° a 11°, o Vocacional, o P...",Únicamente los fines de semana.,Buses intermunicipales,Por compromisos personales o familiares,Poseo licencia de conducción vigente o próxima...,Sí,Diariamente.,Varios vehículos.,NaN,,"Sí, comparto mi vehículo personal con familiar...","Automóvil (carros, camionetas, entre otros);",No,Posibilidad de generar ingresos como propietar...,Posibles daños o mal uso del vehículo rentado;...,No,NaN,NaN,NaN,No,NaN,,NaN,,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,,NaN,"¡Sí, me apuntaría en el presente o en el futuro!",Por horas.;,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,Revisar 49H,Entre $15.000 a $30.000 la hora.;,No me encuentro interesado en rentar por días.;,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,NaN,Clara,Neutral - Es un buen concepto que requiere más...,"Con un chatbot (Sea por plataforma, Whatsapp, ...",19,"[18, 20)"

## Limpieza y Conteo | P50- Otras prioridades para rentar con calma (clientes) [Abierta]

In [317]:
mapeo_P50_motivos_para_rentar_con_calma = {
    'Si lo entregan tanqueado o no' : ['Otro: El vehículo viene tanqueado'],
    
    'Un buen seguro' : ['Otro: Que el vehículo tenga seguro propio'],
    'Qué tenga un buen seguro' : ['Otro: Que el vehículo tenga seguro propio'],
    
    'Antecedentes' : ['Otro: Verificación de antecedentes de Propietarios y Vehículos'],
    
    'Condiciones claras' : ['Revisar 49F'],
    
    'punto de recogida y punto de entrega del vehiculo' : ['Revisar 49G'],
    
    'estado del vehículo' : ['Revisar 49H'],
    'Carro en buen estado' : ['Revisar 49H'],
    'Q estén óptimas condiciones' : ['Revisar 49H'],
    'Los papeles al día del carro' : ['Revisar 49H'],
    'Estado de espejos y direccionales' : ['Revisar 49H'],
    'Estado del vehículo en llantas y limpieza' : ['Revisar 49H'],
    'El estado del carro, no solo en la carrocería y accesorios sino en aspectos de motor y funcionamiento interno de este' : ['Revisar 49H'],
    
    'Las condiciones físicas y mecánicas óptimas para conducirlo y en caso de fallas reportarlo, también la gasolina es importante' : ['Revisar 49H', 'Otro: El vehículo viene tanqueado'],
    
    'Especificaciones en el nivel de gasolina, por ejemplo, de tener un bajo nivel de gasolina el usuario se enfrenta a tener que rellenar el tanque con su propio dinero y si no se especifica en el contrato (Por ejemplo, que cada entrega debe tener como mínimo un nivel de gasolina) el usuario no puede apelar a nada' : ['Revisar 49H', 'Otro: El vehículo viene tanqueado'],
    
    'AGILIDAD EN LA RENTA' : ['Revisar 45I'],
    
    '.' : [''],
    '..' : [''],
    '…' : [''],
    '...' : [''],
    'Sii' : [''],
    'No se' : [''],
    'Ninguno' : [''],
    'Ninguna' : [''],
    'No aplica' : [''],
    'Movimiento' : [''],
    'Ningún otro' : [''],
    'La confianza' : [''],
    'Funcionamiento' : [''],
    'Mantenimiento del vehiculo' : [''],
    'Vehículo preferiblemente nuevo' : [''],
    'Historial de kilometraje y recomendación uso' : [''],
}

# Mapeamos las respuestas en la columna 'P50N-Otros_Puntos_Confianza_para_Rentar[P41]'
df_FlexDrive = mapeo_respuestas(df_FlexDrive, 'P50N-Otros_Puntos_Confianza_para_Rentar[P41]', mapeo_P50_motivos_para_rentar_con_calma)


# Conteo de respuestas (por agrupación) en la columna 'P50N-Otros_Puntos_Confianza_para_Rentar[P41]'
display(df_FlexDrive["P50N-Otros_Puntos_Confianza_para_Rentar[P41]"].value_counts())


# Conteo de respuestas (individuales) en la columna 'P50N-Otros_Puntos_Confianza_para_Rentar[P41]'
display(df_FlexDrive["P50N-Otros_Puntos_Confianza_para_Rentar[P41]"].str.split(";").explode().value_counts())


df_FlexDrive[df_FlexDrive["P50N-Otros_Puntos_Confianza_para_Rentar[P41]"].str.contains("Revisar")]

P50N-Otros_Puntos_Confianza_para_Rentar[P41]
                                                                  371
Revisar 49H                                                         7
Revisar 49H;Otro: El vehículo viene tanqueado                       2
Otro: Que el vehículo tenga seguro propio                           2
Revisar 49G                                                         1
Revisar 49F                                                         1
Revisar 45I                                                         1
Otro: El vehículo viene tanqueado                                   1
Otro: Verificación de antecedentes de Propietarios y Vehículos      1
Name: count, dtype: int64

P50N-Otros_Puntos_Confianza_para_Rentar[P41]
                                                                  371
Revisar 49H                                                         9
Otro: El vehículo viene tanqueado                                   3
Otro: Que el vehículo tenga seguro propio                           2
Revisar 49G                                                         1
Revisar 49F                                                         1
Revisar 45I                                                         1
Otro: Verificación de antecedentes de Propietarios y Vehículos      1
Name: count, dtype: int64

,Fecha_Presentación,Duración_mmss,P1-Autorización,P2-Edad,P3-País,P4-Ciudad,P5-Género,P6-Estrato,P7-Actividad_Actual_Multi,P8-Nivel_Educativo,P9-Frecuencia_Uso_Servicios_Públicos,P10-Servicios_Públicos_Usados_Multi,P11-Motivo_Desplazamiento_Multi,P12-Estado_Licencia_Conducción,P13-Posee_Veh_Propio,P14-Frecuencia_Uso_Veh[P13],P15-Cantidad_Veh_Propios[P13],P16-Modo_Uso_Veh[P15-U],P17-Tipo_Veh[P15-U],P18-Modo_Uso_Veh[P15-Multi],P19-Tipo_Veh[P15-Multi],P20-Conoce_P2P,P21-Beneficios_P2P,P22-Desventajas_P2P,P23-Ha_Rentado_Su_Veh,P24N-Forma_Renta[P21],P25N-Aspectos_Positivos_Exp[P21],P26N-Aspectos_Negativos_Exp2[P21],P27-Ha_Tomado_En_Renta,P28N-Lugar_donde_Rentó[P25],P29N-Entidades_Donde_Rentó[P25],P30N-Beneficios_Experiencia[P25],P31N-Desventajas_Experiencia[P25],P32-Interés_Propietario,P33-Modo_Preferido_Renta_Veh[P30],P34[A]-Prioridad:Seguro_Vehicular[P30],P34[B]-Prioridad:GPS_Vehicular[P30],P34[C]-Prioridad:Autentificar_Todos_Los_Users[P30],P34[D]-Prioridad:Seguridad_Pagos_Plataforma[P30],P34[E]-Prioridad:Comunicación_Directa_Cliente[P30],P34[F]-Prioridad:Apoyo_Precios[P30],P34[G]-Prioridad:Contratos_Automáticos[P30],P34[H]-Prioridad:Variedad_Pagos[P30],...,P34[K]-Prioridad:Asistencia_Legal[P30],P34[L]-Prioridad:Apoyo_Cómo_Cobrar[P30],P35N-Otras_Prioridades[P30],P36-Modelo_Confianza_Multi[P30],P37-Precio_Horas_Propietario_Multi[P30],P38_Precio_Dia_Propietario_Multi[P30],P39_Recibir_Pagos_Propietario[P30],P40[A]-Confianza:Edad_Experiencia_Cliente[P30],P40[B]-Confianza:Antecedentes_Cliente[P30],P40[C]-Confianza:Medio_Pago_Ofertado[P30],P40[D]-Confianza:Calificación_Que_Tiene_El_Cliente[P30],P40[E]-Confianza:Motivo_Solicitud[P30],P41N-Otros_Motivos_Para_Rentar_Seguro[P30],P42-Pago_FlexDrive_Propietarios[P30],P43-Interés_Cliente,P44-Modo_Preferido_Renta_Veh[P41],P45[A]-Prioridad:Comunicación_Propietario[P41],P45[B]-Prioridad:Facilidad_Variedad_Pagos[P41],P45[C]-Prioridad:Variedad_Seguros[P41],P45[D]-Prioridad:Verificación_Usuarios[P41],P45[E]-Prioridad:Apoyo_Dudas[P42],P45[F]-Prioridad:Precios_y_Ofertas[P41],P45[G]-Prioridad:Comunicación_FlexDrive[P41],P45[H]-Prioridad:Reseñar_Propietarios[P41],P45[I]-Prioridad:Modelo_Renta_en_15MINS[P41],P45[J]-Prioridad:Modelo_Negociación[P41],P46N-Otras_Prioridades_Para_Tomar_en_Renta[41],P47-Precio_Horas_Cliente_Multi[P41],P48-Precio_Dia_Cliente_Multi[P41],P49[A]-Confianza:Negociar_con_Propietario[P41],P49[B]-Confianza:Antigüedad_Veh[P41],P49[C]-Confianza:Medio_de_Pago_Recibido[P41],P49[D]-Confianza:Reseñas_Veh[P41],P49[E]-Confianza:Reseñas_Propietario[P41],P49[F]-Confianza:Claridad_Contrato[P41],P49[G]-Confianza:Punto_Entrega_Devolución_Vehículo[P41],P49[H]-Confianza:Revisión_Tecnicomecánica_Veh[P41],P50N-Otros_Puntos_Confianza_para_Rentar[P41],P51-¿Entiende_FlexDrive?,P52-¿Usaria_FlexDrive?,P53-Preferencias_para_Comunicarse_con_FlexDrive,Duración_Minutos,Duración_Rango
2,2025-05-02,12:27,Acepto.,18-25,Colombia,Tunja (Boyacá),Masculino.,4 - (Medio Alto),Soy freelancer / independiente;Soy estudiante ...,Pregrado universitario (Grado o Licenciatura).,Únicamente los fines de semana.,Buses intermunicipales;Otro: Plataformas digit...,Por compromisos personales o familiares,Poseo licencia de conducción vigente o próxima...,No,NaN,NaN,NaN,,NaN,NaN,No,Aprovechamiento de vehículos particulares inac...,Posibles daños o mal uso del vehículo rentado;...,No,NaN,NaN,NaN,Sí,NaN,Localiza,Facilidad en el acceso al servicio.;Transparen...,Costos elevados en comparación con lo esperado,Sí,Por horas.;Por días (cualquier día).;,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,...,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,,Pueda configurar qué tipo de solicitudes quier...,Entre $15.000 a $30.000 la hora.;,Entre $100.000 a $150.000 el día.;,Un respaldo con un pagaré automatizado por tra...,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,,No estaría interesado en pagar comisión alguna.;,"¡Sí, me apuntaría en el presente o en el futuro!",Por días.;,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🟡Prioridad Media🟡,,Entre $15.000 a $30.000 la hora.;,Entre $100.000 a $150.000 el día.;,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,NaN,Revisar 49G,Clara,Muy probable - Me gustaría inscribirme en la p...,Un chat en la plataforma.;Por llamada telefóni...,12,"[12.0, 14.0)"
9,2025-05-02,02:19,Acepto.,18-25,Colombia,Tunja (Boyacá),Femenino.,5 - (Alto),Soy estudiante en estudios superiores o univer...,Pregrado universitario (Grado o Licenciatura).,Rara vez.,Taxis;Buses municipales,Por estudio,Poseo licencia de conducción vigente o próxima...,No,NaN,NaN,NaN,,NaN,NaN,No,Posibilidad de generar ingresos como propietar...,Posibles daños o mal uso del vehículo rentado;...,No,NaN,NaN,NaN,No,NaN,,NaN,,Sí,Por días (cualquier día).;A disposición person...,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,...,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,REVISAR 40B,Pueda configurar qué tipo de solicitudes quier...,Entre $30.000 a $50.000 la hora.;Entre $50.000...,Entre $200.000 a $250.000 el día.;Entre $250.0...,"En efectivo, antes de entregar el vehículo al ...",🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,Revisar 34B,No estaría interesado en pagar comisión alguna.;,"¡Sí, me apuntaría en el presente o en el futuro!",Por días.;Por horas.;,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,Otro: Coherencia precio-servicio,Entre $15.000 a $30.000 la hora.;,Entre $150.000 a $200.000 el día.;Entre $100.0...,🟡Prioridad Media🟡,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,NaN,🔴Prioridad Alta🔴,Revisar 49H,Clara,Probable - Me gustaría conocer más de la plata...,Por chat con asesor mediante Whatsapp.;,2,"[2.0, 4.0)"
14,2025-05-02,45:47,Acepto.,18-25,Colombia,Tunja (Boyacá),Femenino.,3 - (Medio),Soy estudiante en estudios superiores o univer...,Pregrado universitario (Grado o Licenciatura).,Diariamente.,Buses municipales,Por estudio;Por compromisos personales o famil...,"No poseo licencia, pero estoy interesado en ob...",No,NaN,NaN,NaN,,NaN,NaN,Sí,Mayor flexibilidad en horarios;Mejor negociaci...,Posible uso de vehículos para fines no autoriz...,No,NaN,NaN,NaN,No,NaN,,NaN,,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,,NaN,"¡Sí, me apuntaría en el presente o en el futuro!",Por horas.;,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🟡Prioridad Media🟡,🟡Prioridad Media🟡,🟢Prioridad Baja🟢,🔴Prioridad Alta🔴,,Entre $15.000 a $30.000 la hora.;,Entre $150.000 a $200.000 el día.;,🟡Prioridad Media🟡,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,NaN,NaN,Revisar 49F,Clara,Probable - Me gustaría conocer más de la plata...,Un chat en la plataforma.;,45,"[44.0, 46.0)"
53,2025-05-04,33:17,Acepto.,18-25,Colombia,Tunja (Boyacá),Masculino.,3 - (Medio),Soy estudiante en estudios superiores o univer...,Pregrado universitario (Grado o Licenciatura).,Diariamente.,Taxis;Buses municipales;Otro: Plataformas digi...,Por estudio,Poseo licencia de conducción vigente o próxima...,Sí,Diariamente.,Un único vehículo.,"Ocasionalmente lo comparto con mi familia, ami...","Automóvil (carros, camionetas, entre otros)",NaN,NaN,Sí,Posibilidad de generar ingresos como propietar...,Posibles daños o mal uso del vehículo rentado;...,No,NaN,NaN,NaN,No,NaN,,NaN,,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,,NaN,"¡Sí, me apuntaría en el presente o en el futuro!",Por horas.;Por días.;Por semanas.;,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟢Prioridad Baja🟢,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🟡Prioridad Media🟡,Revisar 49H;Otro: Logística de Apoyo Legal par...,Entre $30.000 a $50.000 la hora.;,Entre $150.000 a $200.000 el día.;,🟢Prioridad Baja🟢,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,Revisar 49H;Otro: El vehículo viene tanqueado,Clara,Neutral - Es un buen concepto que requiere más...,Un chat en la plataforma.;Por chat con asesor ...,33,"[32.0, 34.0)"
60,2025-05-05,17:45,Acepto.,46-55,Colombia,Yopal (Casanare),Masculino.,4 - (Medio Alto),Soy empresario,Especialización o Diplomado de Posgrado (estud...,Rara vez.,Taxis;SITP,Por compromisos personales o familiares;Por tr...,Poseo licencia de conducción vigente o próxima...,Sí,Diariamente.,Un único vehículo.,"Ocasionalmente lo comparto con mi familia, ami...","Automóvil (carros, camionetas, entre otros)",NaN,NaN,No,Aprovechamiento de vehículos particulares inac...,Desconfianza frente a clientes / personas desc...,No,NaN,NaN,NaN,Sí,NaN,Hertz,Tecnología fácil de utilizar (a través de plat...,Información confusa sobre los contratos;Poca o...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,,NaN,"¡Sí, me apuntaría en el presente o en el futuro!",Por días.;,🟡Prioridad Media🟡,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🟡Prioridad Media🟡,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,🟡Prioridad Media🟡,🟢Prioridad Baja🟢,🟢Prioridad Baja🟢,Revisar 45F,Entre $30.000 a $50.000 la hora.;,Entre $150.000 a $200.000 el día.;,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,Revisar 45I,Clara,Probable - Me gustaría conocer más de la plata...,Un chat en la plataforma.;Por llamada telefóni...,17,"[16.0, 18.0)"
78,2025-05-06,15:36,Acepto.,26-35,Colombia,Medellín (Antioquia),Femenino.,4 - (Medio Alto),Soy freelancer / independiente,Pregrado universitario (Grado o Licenciatura).,Únicamente entre semana.,Buses municipales;Buses intermunicipales;Taxis...,Por compromisos personales o familiares;Por tr...,Poseo licencia de conducción vigente o próxima...,No,NaN,NaN,NaN,,NaN,NaN,No,Posibilidad de generar ingresos como propietar...,Posibles daños o mal uso del vehículo rentado;...,No,NaN,NaN,NaN,Sí,Colombia,,Facilidad en el acceso al servicio.;Rapidez en...,Información confusa sobre los contratos;Costos...,Sí,Solo durante semana (lunes a viernes).;Por hor...,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,...,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,,Reciba solicitudes y pueda aceptarlas o denega...,Entre $15.000 a $30.000 la hora.;,Entre $150.000 a $200.000 el día.;,"Por transacción bancaria inmediata, al finaliz...",🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,,Aceptaría pagar una comisión del 4% al 9% por ...,"¡Sí, me apuntaría en el presente o en el futuro!",Por horas.;Por días.;,🟢Prioridad Baja🟢,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🟡Prioridad Media🟡,,Entre $30.000 a $50.000 la hora.;,Entre $100.000 a $150.000 el día.;Entre $150.0...,🟡Prioridad Media🟡,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,Revisar 49H;Otro: El vehículo viene tanqueado,Clara,Muy probable - Me gustaría inscribirme en la p...,Un chat en la plataforma.;Por llamada telefóni...,15,"[14.0, 16.0)"
245,2025-05-21,09:07,Acepto.,26-35,Colombia,Funza (Cundinamarca),Femenino.,2 - (Bajo - Medio),Soy empleado;Soy estudiante en estudios superi...,Formación Técnica o Tecnológica.,Rara vez.,,Por trabajo,"No poseo licencia, y tampoco estoy interesado ...",Sí,Diariamente.,Un único vehículo.,"No, es un vehículo completamente propio.",Otro: Bicicleta convencional,NaN,NaN,Sí,Mayor flexibilidad en horarios;Mejor negociaci...,Posibles daños o mal uso del vehículo rentado;...,No,NaN,NaN,NaN,No,NaN,,NaN,,Sí,Solo durante semana (lunes a viernes).;,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,...,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,Otro: Elementos de Seguridad Vial y Protección...,Reciba solicitudes y pueda aceptarlas o denega...,Entre $30.000 a $50.000 la hora.;,Entre $100.000 a $150.000 el día.;Entre $150.0...,"Por transacción bancaria inmediata, una vez ap...",🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,Revisar 40B,Preferiría pagar una suscripción mensual.;,"¡Sí, me apuntaría en el presente o en el futuro!",Por días.;Por semanas.;,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,Revisar 49G,Entre $15.000 a $30.000 la hora.;Entre $30.000...,Entre $100.000 a $150.000 el día.;Entre $150.0...,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,Revisar 49H,Clara,Muy probable - Me gustaría inscribirme en la p...,Un chat en la plataforma.;Por correo electróni...,9,"[8.0, 10.0)"
319,2025-05-23,09:53,Acepto.,46-55,Colombia,Samacá (Boyacá),Femenino.,3 - (Medio),Soy empleado,Especialización o Diplomado de Posgrado (estud...,Rara vez.,Buses intermunicipales,Por trabajo,Poseo licencia de conducción vigente o próxima...,Sí,Diariamente.,Un único vehículo.,"No, es un vehículo completamente propio.","Automóvil (carros, camionetas, entre otros)",NaN,NaN,No,Posibilidad de generar ingresos como propietar...,Posibles daños o mal uso del vehículo rentado,No,NaN,NaN,NaN,Sí,En el exterior,Avis,Facilidad en el acceso al servicio.;,Costos elevados en comparación con lo esperado,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,,NaN,"¡Sí, me apuntaría en el presente o en el futuro!",Por días.;,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,,No me encuentro interesado en rentar por horas.;,Entre $100.000 a $150.000 el día.;,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,Revisar 49H,Clara,Probable - Me gustaría conocer más de la plata...,Un chat en la plataforma.;,9,"[8.0, 10.0)"
325,2025-05-23,19:17,Acepto.,18-25,Colombia,Tunja (Boyacá),Masculino.,3 - (Medio),Soy estudiante en estudios superiores o univer...,Pregrado universitario (Grado o Licenciatura).,Únicamente entre semana.,Taxis,Por estudio;Por trabajo,"No poseo licencia, pero estoy interesado en ob...",Sí,Solo durante fines de semana.,Un único vehículo.,"Ocasionalmente lo comparto con mi familia, ami...",Scooter,NaN,NaN,Sí,Posibilidad de generar ingresos como propietar...,Posibles daños o mal uso del vehículo rentado;...,No,NaN,NaN,NaN,Sí,Tanto en Colombia como en el exterior,,Facilidad en el acceso al servicio.;Rapidez en...,Dificultad para solicitar o acceder al servici...,Sí,Por días (cualquier día).;Solo los fines de se...,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,...,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,Otro: Que el vehículo reciba un uso correcto,Reciba solicitudes y pueda aceptarlas o denega...,Entre $15.000 a $30.000 la hora.;Entre $30.000...,Entre $100.000 a $150.000 el día.;Entre $150.0...,"En efectivo, antes de entregar el vehículo al ...",🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,,Aceptaría pagar una comisión del 4% al 9% por ...,"¡Sí, me apuntaría en el presente o en el futuro!",Por horas.;Por días.;Por semanas.;,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,Revisar 49H,Entre $15.000 a $30.000 la hora.;Entre $30.000...,Entre $100.000 a $150.000 el día.;Entre $150.0...,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,Revisar 49H,Clara,Muy probable - Me gustaría inscribirme en la p...,Un chat en la plataforma.;,19,"[18.0, 20.0)"
349,2025-05-24,12:03,Acepto.,18-25,Colombia,Sogamoso (Boyacá),Femenino.,3 - (Medio),Soy estudiante en estudios superiores o univer...,Formación Técnica o Tecnológica.,Rara vez.,Buses municipales;Buses intermunicipales,Por trabajo,"No poseo licencia, pero estoy interesado en ob...",No,NaN,NaN,NaN,,NaN,NaN,No,Mayor flexibilidad en horarios;Promueve la eco...,Posibles daños o mal uso del vehículo rentado;...,No,NaN,NaN,NaN,No,NaN,,NaN,,Sí,A disposición personal.;Solo durante semana (l...,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,...,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,REVISAR 40B,Reciba solicitudes y pueda aceptarlas o denega...,Entre $15.000 a $30.000 la hora.;,Entre $100.000 a $150.000 el día.;,"En efectivo, antes de entregar el vehículo al ...",🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,,Preferiría pagar una suscripción mensual.;,"¡Sí, me apuntaría en el presente o en el futuro!",Por semanas.;,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,Revisar 49H,Entre $15.000 a $30.000 la hora.;,Entre $100.000 a $150.000 el día.;,🟡Prioridad Media🟡,🟡Prioridad Media🟡,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,🔴Prioridad Alta🔴,Revisar 49H,Clara,Probable - Me gustaría conocer más de la plata...,Por chat con asesor mediante Whatsapp.;Por lla...,12,"[12.0, 14.0)"

## Limpieza y Conteo | P53- ¿Cómo prefieren comunicarse con Flex Drive? [Multi]

In [318]:
mapeo_P53_Comunicarte_con_FlexDrive = {
    'Ninguno' : ["RESPUESTA INVÁLIDA - INDIFERENTE"],
    'Ninguna' : ["RESPUESTA INVÁLIDA - INDIFERENTE"],
    'No me interesa' : ["RESPUESTA INVÁLIDA - INDIFERENTE"],
    'No me interesa comunicarme' : ["RESPUESTA INVÁLIDA - INDIFERENTE"],
    
    'Personalizado' : ['RESPUESTA INVÁLIDA'],
}

# Mapeamos las respuestas en la columna 'P50N-Otros_Puntos_Confianza_para_Rentar[P41]'
df_FlexDrive = mapeo_respuestas(df_FlexDrive, 'P53-Preferencias_para_Comunicarse_con_FlexDrive', mapeo_P53_Comunicarte_con_FlexDrive)

# Conteo de respuestas (por agrupación) en la columna 'P53-Preferencias_para_Comunicarse_con_FlexDrive'
display(df_FlexDrive["P53-Preferencias_para_Comunicarse_con_FlexDrive"].value_counts())

# Conteo de respuestas (individuales) en la columna 'P53-Preferencias_para_Comunicarse_con_FlexDrive'
display(df_FlexDrive["P53-Preferencias_para_Comunicarse_con_FlexDrive"].str.split(";").explode().value_counts())

P53-Preferencias_para_Comunicarse_con_FlexDrive
Un chat en la plataforma                                                                                                                                                     66
Por chat con asesor mediante Whatsapp                                                                                                                                        50
Por llamada telefónica                                                                                                                                                       34
Por correo electrónico                                                                                                                                                       32
Un chat en la plataforma;Por llamada telefónica;Por chat con asesor mediante Whatsapp                                                                                        25
Un chat en la plataforma;Por chat con asesor mediante Whatsapp                                                                                                               24
Con un chatbot (Sea por plataforma, Whatsapp, u otro medio.)                                                                                                                 17
Por llamada telefónica;Por chat con asesor mediante Whatsapp                                                                                                                 16
Un chat en la plataforma;Por llamada telefónica                                                                                                                              15
Un chat en la plataforma;Por chat con asesor mediante Whatsapp;Con un chatbot (Sea por plataforma, Whatsapp, u otro medio.)                                                  11
Por chat con asesor mediante Whatsapp;Un chat en la plataforma                                                                                                                7
Un chat en la plataforma;Con un chatbot (Sea por plataforma, Whatsapp, u otro medio.)                                                                                         7
Un chat en la plataforma;Por correo electrónico;Por llamada telefónica;Por chat con asesor mediante Whatsapp                                                                  7
Por chat con asesor mediante Whatsapp;Por llamada telefónica                                                                                                                  6
Un chat en la plataforma;Por llamada telefónica;Por chat con asesor mediante Whatsapp;Con un chatbot (Sea por plataforma, Whatsapp, u otro medio.)                            5
Un chat en la plataforma;Por chat con asesor mediante Whatsapp;Por llamada telefónica                                                                                         4
Un chat en la plataforma;Por correo electrónico                                                                                                                               4
Un chat en la plataforma;Por llamada telefónica;Por correo electrónico                                                                                                        4
Un chat en la plataforma;Por correo electrónico;Por llamada telefónica;Por chat con asesor mediante Whatsapp;Con un chatbot (Sea por plataforma, Whatsapp, u otro medio.)     4
Por llamada telefónica;Un chat en la plataforma                                                                                                                               4
Por chat con asesor mediante Whatsapp;Con un chatbot (Sea por plataforma, Whatsapp, u otro medio.)                                                                            3
RESPUESTA INVÁLIDA - INDIFERENTE                                                                                                                                              3
Por correo electrónico;Por chat con asesor mediante Whatsapp                                                                                                                  3
Por llamada telefónica;Por chat con asesor mediante Whatsapp;Un chat en la plataforma                                                                                         3
Un chat en la plataforma;Por llamada telefónica;Por correo electrónico;Por chat con asesor mediante Whatsapp                                                                  2
Un chat en la plataforma;Por llamada telefónica;Con un chatbot (Sea por plataforma, Whatsapp, u otro medio.)                                                                  2
Un chat en la plataforma;Por correo electrónico;Por chat con asesor mediante Whatsapp                                                                                         2
Por correo electrónico;Por llamada telefónica;Por chat con asesor mediante Whatsapp                                                                                           2
Por chat con asesor mediante Whatsapp;Por llamada telefónica;Un chat en la plataforma;Por correo electrónico                                                                  2
Por llamada telefónica;Por correo electrónico;Por chat con asesor mediante Whatsapp;Con un chatbot (Sea por plataforma, Whatsapp, u otro medio.);Un chat en la plataforma     1
Por llamada telefónica;Un chat en la plataforma;Con un chatbot (Sea por plataforma, Whatsapp, u otro medio.)                                                                  1
Por llamada telefónica;Un chat en la plataforma;Por chat con asesor mediante Whatsapp                                                                                         1
Un chat en la plataforma;Por llamada telefónica;Por correo electrónico;Por chat con asesor mediante Whatsapp;Con un chatbot (Sea por plataforma, Whatsapp, u otro medio.)     1
RESPUESTA INVÁLIDA                                                                                                                                                            1
Un chat en la plataforma;Por correo electrónico;Por llamada telefónica;Con un chatbot (Sea por plataforma, Whatsapp, u otro medio.);Por chat con asesor mediante Whatsapp     1
Un chat en la plataforma;Con un chatbot (Sea por plataforma, Whatsapp, u otro medio.);Por llamada telefónica                                                                  1
Con un chatbot (Sea por plataforma, Whatsapp, u otro medio.);Por llamada telefónica                                                                                           1
Por llamada telefónica;Por correo electrónico;Un chat en la plataforma                                                                                                        1
Por chat con asesor mediante Whatsapp;Con un chatbot (Sea por plataforma, Whatsapp, u otro medio.);Por correo electrónico;Por llamada telefónica                              1
Por llamada telefónica;Por correo electrónico                                                                                                                                 1
Un chat en la plataforma;Por llamada telefónica;Por chat con asesor mediante Whatsapp;Por correo electrónico                                                                  1
Por llamada telefónica;Con un chatbot (Sea por plataforma, Whatsapp, u otro medio.);Por chat con asesor mediante Whatsapp                                                     1
Por correo electrónico;Un chat en la plataforma                                                                                                                               1
Un chat en la plataforma;Por llamada telefónica;Por chat con asesor mediante Whatsapp;Con un chatbot (Sea por plataforma, Whatsapp, u otro medio.);Por correo electrónico     1
Por chat con asesor mediante Whatsapp;Un chat en la plataforma;Por llamada telefónica                                                                                         1
Por llamada telefónica;Por correo electrónico;Un chat en la plataforma;Por chat con asesor mediante Whatsapp;Con un chatbot (Sea por plataforma, Whatsapp, u otro medio.)     1
Un chat en la plataforma;Por chat con asesor mediante Whatsapp;Por correo electrónico                                                                                         1
Por chat con asesor mediante Whatsapp;Un chat en la plataforma;Con un chatbot (Sea por plataforma, Whatsapp, u otro medio.)                                                   1
Por llamada telefónica;Por chat con asesor mediante Whatsapp;Con un chatbot (Sea por plataforma, Whatsapp, u otro medio.)                                                     1
Un chat en la plataforma;Por correo electrónico;Por chat con asesor mediante Whatsapp;Con un chatbot (Sea por plataforma, Whatsapp, u otro medio.)                            1
Por correo electrónico;Por chat con asesor mediante Whatsapp;Con un chatbot (Sea por plataforma, Whatsapp, u otro medio.)                                                     1
Por chat con asesor mediante Whatsapp;Con un chatbot (Sea por plataforma, Whatsapp, u otro medio.);Por llamada telefónica                                                     1
Name: count, dtype: int64

P53-Preferencias_para_Comunicarse_con_FlexDrive
Un chat en la plataforma                                        213
Por chat con asesor mediante Whatsapp                           192
Por llamada telefónica                                          152
Por correo electrónico                                           75
Con un chatbot (Sea por plataforma, Whatsapp, u otro medio.)     64
RESPUESTA INVÁLIDA - INDIFERENTE                                  3
RESPUESTA INVÁLIDA                                                1
Name: count, dtype: int64

In [319]:
df_FlexDrive[df_FlexDrive["P53-Preferencias_para_Comunicarse_con_FlexDrive"] == "No me interesa comunicarme;"]

Empty DataFrame
Columns: [Fecha_Presentación, Duración_mmss, P1-Autorización, P2-Edad, P3-País, P4-Ciudad, P5-Género, P6-Estrato, P7-Actividad_Actual_Multi, P8-Nivel_Educativo, P9-Frecuencia_Uso_Servicios_Públicos, P10-Servicios_Públicos_Usados_Multi, P11-Motivo_Desplazamiento_Multi, P12-Estado_Licencia_Conducción, P13-Posee_Veh_Propio, P14-Frecuencia_Uso_Veh[P13], P15-Cantidad_Veh_Propios[P13], P16-Modo_Uso_Veh[P15-U], P17-Tipo_Veh[P15-U], P18-Modo_Uso_Veh[P15-Multi], P19-Tipo_Veh[P15-Multi], P20-Conoce_P2P, P21-Beneficios_P2P, P22-Desventajas_P2P, P23-Ha_Rentado_Su_Veh, P24N-Forma_Renta[P21], P25N-Aspectos_Positivos_Exp[P21], P26N-Aspectos_Negativos_Exp2[P21], P27-Ha_Tomado_En_Renta, P28N-Lugar_donde_Rentó[P25], P29N-Entidades_Donde_Rentó[P25], P30N-Beneficios_Experiencia[P25], P31N-Desventajas_Experiencia[P25], P32-Interés_Propietario, P33-Modo_Preferido_Renta_Veh[P30], P34[A]-Prioridad:Seguro_Vehicular[P30], P34[B]-Prioridad:GPS_Vehicular[P30], P34[C]-Prioridad:Autentificar_Todos_Los_Users[P30], P34[D]-Prioridad:Seguridad_Pagos_Plataforma[P30], P34[E]-Prioridad:Comunicación_Directa_Cliente[P30], P34[F]-Prioridad:Apoyo_Precios[P30], P34[G]-Prioridad:Contratos_Automáticos[P30], P34[H]-Prioridad:Variedad_Pagos[P30], P34[I]-Prioridad:Reseñas_Clientes[P30], P34[J]-Prioridad:Contacto_FlexDrive[P30], P34[K]-Prioridad:Asistencia_Legal[P30], P34[L]-Prioridad:Apoyo_Cómo_Cobrar[P30], P35N-Otras_Prioridades[P30], P36-Modelo_Confianza_Multi[P30], P37-Precio_Horas_Propietario_Multi[P30], P38_Precio_Dia_Propietario_Multi[P30], P39_Recibir_Pagos_Propietario[P30], P40[A]-Confianza:Edad_Experiencia_Cliente[P30], P40[B]-Confianza:Antecedentes_Cliente[P30], P40[C]-Confianza:Medio_Pago_Ofertado[P30], P40[D]-Confianza:Calificación_Que_Tiene_El_Cliente[P30], P40[E]-Confianza:Motivo_Solicitud[P30], P41N-Otros_Motivos_Para_Rentar_Seguro[P30], P42-Pago_FlexDrive_Propietarios[P30], P43-Interés_Cliente, P44-Modo_Preferido_Renta_Veh[P41], P45[A]-Prioridad:Comunicación_Propietario[P41], P45[B]-Prioridad:Facilidad_Variedad_Pagos[P41], P45[C]-Prioridad:Variedad_Seguros[P41], P45[D]-Prioridad:Verificación_Usuarios[P41], P45[E]-Prioridad:Apoyo_Dudas[P42], P45[F]-Prioridad:Precios_y_Ofertas[P41], P45[G]-Prioridad:Comunicación_FlexDrive[P41], P45[H]-Prioridad:Reseñar_Propietarios[P41], P45[I]-Prioridad:Modelo_Renta_en_15MINS[P41], P45[J]-Prioridad:Modelo_Negociación[P41], P46N-Otras_Prioridades_Para_Tomar_en_Renta[41], P47-Precio_Horas_Cliente_Multi[P41], P48-Precio_Dia_Cliente_Multi[P41], P49[A]-Confianza:Negociar_con_Propietario[P41], P49[B]-Confianza:Antigüedad_Veh[P41], P49[C]-Confianza:Medio_de_Pago_Recibido[P41], P49[D]-Confianza:Reseñas_Veh[P41], P49[E]-Confianza:Reseñas_Propietario[P41], P49[F]-Confianza:Claridad_Contrato[P41], P49[G]-Confianza:Punto_Entrega_Devolución_Vehículo[P41], P49[H]-Confianza:Revisión_Tecnicomecánica_Veh[P41], P50N-Otros_Puntos_Confianza_para_Rentar[P41], P51-¿Entiende_FlexDrive?, P52-¿Usaria_FlexDrive?, P53-Preferencias_para_Comunicarse_con_FlexDrive, Duración_Minutos, Duración_Rango]
Index: []

[0 rows x 88 columns]

## Cierre de Limpieza | Exportación del .csv

In [320]:
# Subir df_FlexDrive a un archivo csv con separado ';'
df_FlexDrive.to_csv('../../docs/poblaciones/df_FlexDrive_Insights.csv', sep=';', index=False, encoding='utf-8-sig')